### ISSUE TITLE
issue with JSCS package

### ISSUE THREAD

**Issue by RYG81** [Glavin001/atom-beautify#1015]
I am using JSCS to fix my javascript code styling. To my surprise whenever I beautify my code JSCS gives error to all line. Can you fix this?

**Comment by prettydiff** [comment]
JSCS has a lot of different options and supports various different style guides, which means we don't know which aspects of JSCS are failing.  Could you also provide a debug.md file so that we can see the code you are using and the beautifier you have selected?  If we cannot reproduce the problem we cannot fix it.
