### ISSUE TITLE
Could not find 'php'. The program may not be installed.

### ISSUE THREAD

**Issue by joergmold** [Glavin001/atom-beautify#1016]
When I try to beautify a php file I get the error message "Could not find 'php'. The program may not be installed."

I already set the path to the php-cs-fixer.phar in the package settings. I also set the path to php in my windows system path variable. If I type "php -v" on the command line i get my php version and if I type "where php" i get the path to php. So php seems to work properly.

I am also using the php linter atom package and there is no problem with finding php.

**Comment by prettydiff** [comment]
The PHP beautifier is written in PHP, so you must have PHP installed locally for this to run.

**Comment by QiiSyhx** [comment]
i have the same problem.
error info.
Could not find 'php'. The program may not be installed.
See http://php.net/manual/en/install.php for program installation instructions.
Your program is properly installed if running 'where.exe php' in your CMD prompt returns an absolute path to the executable. If this does not work then you have not installed the program correctly and so Atom Beautify will not find the program. Atom Beautify requires that the program be found in your PATH environment variable. 
Note that this is not an Atom Beautify issue if beautification does not work and the above command also does not work: this is expected behaviour, since you have not properly installed your program. Please properly setup the program and search through existing Atom Beautify issues before creating a new issue. See https://github.com/Glavin001/atom-beautify/search?q=php&type=Issues for related Issues and https://github.com/Glavin001/atom-beautify/tree/master/docs for documentation. If you are still unable to resolve this issue on your own then please create a new issue and ask for help.

**Comment by joergmold** [comment]
The problem could be that the windows system PATH variable is not correctly passed to atom. Maybe it would be a good idea to have an option in the atom beautify settings where the path to php can be set manually (like the path to php-cs-fixer.phar).

However, I am also using the php linter package and there I do not need to set the path to php (although I would have the option to do so).

**Comment by QiiSyhx** [comment]
i have used php-fmt instead.

**Comment by ethanclevenger91** [comment]
Also getting this error. Attempted to add the debug but it just copied `e` to my clipboard.

Here's the stack trace:

```
Error: Could not find 'php'. The program may not be installed.
    at PHPCSFixer.module.exports.Beautifier.commandNotFoundError (file:///C:/Users/Ethan/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:196:14)
    at file:///C:/Users/Ethan/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:292:25
    at tryCatcher (C:\Users\Ethan\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Ethan\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (C:\Users\Ethan\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (C:\Users\Ethan\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (C:\Users\Ethan\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:679:18)
    at Async._drainQueue (C:\Users\Ethan\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\Ethan\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:148:10)
    at Async.drainQueues (C:\Users\Ethan\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
    at process._tickCallback (node.js:392:9)
```

**Comment by UziTech** [comment]
check out issue #1054. Might solve it

**Comment by joergmold** [comment]
Thank you very much. That indeed solved the problem. The systems environment variable PATH has to be in uppercase.

I am a little worried that my change from "path" to "PATH" could have some unwated effects, but it seems that in Windows system variables are case insensitive.

I also still think it might be a good idea to have an option in the atom-beautify settings where the path to php can be set manually.

**Comment by joergmold** [comment]
I found another problem.

When I open atom via the shortcut on my desktop, beautification works fine.

However, when I right click on a folder in explorer and select "Open with Atom", beautification simply does not happen. There is no error message, I can see the "beautification in progess" window, but the code stays as ugly as it is.

**Comment by prettydiff** [comment]
@joergmold That sounds like it should be a new and unrelated issue.

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.
