### ISSUE TITLE
Error: Cannot find module build-options.js

### ISSUE THREAD

**Issue by roccomuso** [Glavin001/atom-beautify#1072]
`
module.js:340
    throw err;
          ^
Error: Cannot find module '/tmp/apm-install-dir-116617-20638-ztkfdh/node_modules/atom-beautify/script/build-options.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/root/.atom/.apm/.apmrc" "--userconfig" "/root/.atom/.apmrc" "install" "/tmp/d-116617-20638-1caf4s7/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.9 postinstall: `node script/build-options.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the atom-beautify@0.29.9 postinstall script 'node script/build-options.js'.
npm ERR! This is most likely a problem with the atom-beautify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node script/build-options.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.
`
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Looks like a dependency failed to download.  I recommend trying this from the command line `apm install atom-beautify`.  Please let us know if this resolves the problem.

**Comment by roccomuso** [comment]
Same error also doing <code>apm install atom-beautify</code>

**Comment by primehat23** [comment]
I got a E: Unable to locate package apm. 
Could this be my ubuntu disto

**Comment by prettydiff** [comment]
@Glavin001 Any idea?

**Comment by phatpeth** [comment]
face the same problem.

**Comment by Glavin001** [comment]
Running `apm install atom-beautify` returns `Unable to locate package apm.`? If so, then this is an Atom/apm issue and please contact https://github.com/atom/apm

For the issue that `script/build-options.js` cannot be found, this is also an apm issue because that file SHOULD be downloaded and installed, however I do want to reduce places where Atom/apm can cause problems and the `build-options.js` script is one of them. I am currently working on rewriting Atom-Beautify entirely with a lot more features, bug fixes, and enhancements. However, this will take time and I am currently away on vacation for two weeks.

My recommendation is to contact the Atom team at https://github.com/atom/apm and confirm your Atom and apm installation is properly functioning, since the `script/build-options.js` file should be downloaded by apm upon install and thus this issue should not arrise.

Thank you for your patience and I apologize for the inconvenience. This is definitely an issue I will be addressing when I can.

**Comment by phatpeth** [comment]
For Ubuntu, I solved this problem by re-install Atom on the root path, which has usr and tmp folder

> [root@username/]

and then install atom-beautify here.

but on Windows 10, I still have no idea.

**Comment by Glavin001** [comment]
I've merged https://github.com/Glavin001/atom-beautify/pull/1598 which should resolve these issues.

Published to v0.29.21.
