### ISSUE TITLE
Support configuration discovery for stylish-haskell

### ISSUE THREAD

**Issue by JustusAdam** [Glavin001/atom-beautify#1074]
# Description

The Haskell beautifier used internally (`stylish-haskell`) supports its own configuration file either via command line parameter `-c` or implicitly by finding a file called `.stylish-haskell.yaml` in the directory, or an ancestor of the directory, where `stylish-haskell` is being run from.

Currently when I run `Beautify Editor` the configuration file which I placed in my project root folder is not being used.

This could be due to the tool being run from a different directory or in some sandbox like manner where it does not gain access to the configuration.

It would be nice if stylish-haskell ran from at least my project root to use the project wide settings for beautification.
# Proposed change

Invoke `stylish-haskell` from project root **or** from the directory containing the file in question, this should in theory traverse ancestors until it finds the .stylish-haskell.yaml in the project root.

**Comment by rogerbosman** [comment]
Issue still relevant: using `atom-beautify`, we can only set a global `.stylish-haskell.yaml` settings file, as it will not detect files in the project root.

This change would be nice for two reasons:
* Avoid implicit settings
  Ideally, I'd have settings files on a per-project basis, so that is obvious where the behavior is coming from. If not, I will forget either the location or even the existence of the configuration, leading to issues.
* Advanced settings
  Stylish Haskell allows for some extensive configuration, settings that go well beyond overall style preference (which arguably shouldn't change much project to project) requiring per-project settings.
