### ISSUE TITLE
formatting jsp code cause running errors.

### ISSUE THREAD

**Issue by lipei86** [Glavin001/atom-beautify#1107]
# Description

We usually use jstl or struts tags in jsp code, but tag's attribute value after beautified will be inserted some space which cause running errors. 
For example, we entered the following code:
```
<a href="<s:url namespace="/taskdist" action="index"></s:url>" class="btn btn-primary" role="button">Task Index</a>
```
after beautified, the attribute value of struts tags has been inserted a space, and the space cause running errors:
```
<a href="<s:url namespace=" /taskdist" action=" index"></s:url>" class="btn btn-primary" role="button">Task Index</a>
```

# Expected Results

The beautified code should have looked like:

```
<a href="<s:url namespace="/taskdist" action="index"></s:url>" class="btn btn-primary" role="button">Task Index</a>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

**Comment by prettydiff** [comment]
Would you mind generating Atom Beautify's debug.md file and pasting it into a gist?  This will help us identify which beautifier you are using and which grammar Atom thinks you are using.

**Comment by lipei86** [comment]
@prettydiff Here is the gist url: https://gist.github.com/a3e4667be3dfd361dd26ee9243e930e5.

**Comment by prettydiff** [comment]
Pretty Diff defect.  I am working it now.

**Comment by prettydiff** [comment]
The problem is a collision with the quotes.  The challenge is that I can choose to support one of these, but not both:

    <a attribute="<c:out value="place">something</c:out>">a thing</a>

    <a attribute="if (a<b) do something">a thing</a>

The reason for the dichotomy is that each attribute contains a `<` within quotes.  In one case its a markup delimiter and in another case it isn't.  To make matters worse the JSP embedded tag use quotes for its attribute while it itself is quoted.  That means I have to expect that the attribute value is delimited by double quotes, contains an XML tag delimited by angle braces, and contains contains its own attributes delimited by double quotes.  I can parse this without collision, but only if I presume the angle braces must be delimiters for XML.

The only resolutions I can think of are:

1. Change your JSP attributes to be wrapped in single quotes.  I tried this in Pretty Diff and it instantly solved the problem.
2. Extend Pretty Diff to support embedded tags within attribute values.... but only if the attribute value begins with a delimiter and ends with a delimiter.  Meaning the following would still fail

    <a myAttribute="<c:out cat="meow">furry</c> climber">animal</a>

**Comment by prettydiff** [comment]
This work is done.  I put in some extra effort to ensure that all code examples in my prior comment are possible.  The resolution is published to Pretty Diff release 2.1.1 but will not be available to Atom Beautify until I can release https://github.com/prettydiff/biddle

**Comment by lipei86** [comment]
@prettydiff Thank you for resolving the problem.

**Comment by prettydiff** [comment]
Keeping everybody informed I have fixed biddle.  Check it out now - https://github.com/prettydiff/biddle

I will republish Pretty Diff using biddle in production tomorrow.  I am not ready to give it to Atom Beautify just yet though.  I actually need users to play around with this thing for a bit so that I can get a sense of where the pain points are and just how bad it works for fails for other people.  I wrote a getting started document at https://github.com/prettydiff/biddle/blob/master/documentation/gettingstarted.md

The documentation might be easier to read from the command line though as I included a markdown to CLI parser in biddle.  The number at the end defines the word wrap limit:

    node biddle markdown documentation/gettingstarted.md 80
