### ISSUE TITLE
PHP - tempnam(): file created in the system's temporary directory  

### ISSUE THREAD

**Issue by diego-vieira** [Glavin001/atom-beautify#1108]
# Description
Getting the error below when using php-cs-fixer.
Running php-cs-fixer from the command line works just fine.
Also attached Atom debug console info.
![screen shot 2016-08-03 at 01 39 58](https://cloud.githubusercontent.com/assets/930792/17354032/4dcecdfa-591b-11e6-8aea-35439ce4b60a.jpg)

[ErrorException]                                             
tempnam(): file created in the system's temporary directory  
fix [--config="..."] [--config-file[="..."]] [--dry-run] [--level="..."] [--fixers="..."] [--diff] [--format="..."] [path]

# Debug
Here is a link to the `debug.md` Gist: https://gist.github.com/058a4a8d5646024d14f1468da4178225

# Checklist

- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by diego-vieira** [comment]
never mind, seems a bug with my php 7 binary. installing php 5.6 resolved.

**Comment by StanDog** [comment]
This is not a bug. It is a "bugfix" that was made in PHP 7.1.0 because someone thought, that tempnam() should throw a notice, since it might use different paths for the temporary dir (which is correct). Here is the full list of changes:

http://php.net/ChangeLog-7.php#7.1.0

The bug is listed as "Fixed bug #69489 (tempnam() should raise notice if falling back to temp dir)."

And here is the ticket:

https://bugs.php.net/bug.php?id=69489


Since this is just a notice and the function still works correctly, you can either place the "@" operator infront of the function call "@tempnam()" or set your personal temp path in your php.ini like this:

upload_tmp_dir = C:\php\temp\

I'm not sure if the last one prevents PHP throwing the notice (I use PHP 7.0.9 and didn't tested it), but I think it will work.

**Comment by rakeshjames** [comment]
Well, When I am trying to run the PHP unit test on my local,  i am getting following 
`rakeshjames at Rakeshs-MacBook-Pro in ~/Sites/drupal on 8.5.x [!?]
$ sudo -u _www -E ./vendor/bin/phpunit -c core --filter testMigrateUpgrade
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

Testing 
tempnam(): file created in the system's temporary directory`

It was working fine, till yesterday:( 

`rakeshjames at Rakeshs-MacBook-Pro in ~/Sites/drupal on 8.4.x [!?$]
$ php --version
PHP 7.1.11 (cli) (built: Nov  3 2017 22:18:28) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans`

**Comment by sgmobarak** [comment]
I had this problem (in windows OS) with troydavisson\phrets package and I ended up with a solution like below:
'curl' => [ CURLOPT_COOKIEFILE => @tempnam('/tmp', 'phrets') ]

**Comment by enguez** [comment]
> 
> 
> I had this problem (in windows OS) with troydavisson\phrets package and I ended up with a solution like below:
> 'curl' => [ CURLOPT_COOKIEFILE => @tempnam('/tmp', 'phrets') ]

Can you elaborate your solution?
I am having this same issue with PHRETS.
Thanks!

**Comment by sgmobarak** [comment]
@enguez form my experience, tempnam function works fine in linux but not windows. If we call it with @ sign, then it works for windows. Since, my development environment is running on my windows, I modified this line in the function getDefaultOptions() of \vendor\troydavisson\phrets\src\Session.php file.  In my code, the line number is 481. Better you find and replace tempnam with @tempnam through this file.

Thank you

**Comment by linda-dge** [comment]
The @ sign solved my issue.  Thank you!

**Comment by yasserakbbach** [comment]
I've the same problem :/ could you please guide me how to solve it?!

**Comment by sgmobarak** [comment]
Please go to `\vendor\troydavisson\phrets\src\Session.php` file and find and replace tempnam with @tempnam through this file. Below is the line from my code.
`'curl' => [ CURLOPT_COOKIEFILE => @tempnam('/tmp', 'phrets') ]`

**Comment by sgmobarak** [comment]
Hi @yasserakbbach
Please go to `\vendor\troydavisson\phrets\src\Session.php` file and find and replace tempnam with @tempnam through this file. Below is the line from my code.
`'curl' => [ CURLOPT_COOKIEFILE => @tempnam('/tmp', 'phrets') ]`

**Comment by abdelkhalek-haddany** [comment]
> The @ sign solved my issue. Thank you!

config/cors.php

**Comment by uuf6429** [comment]
The solution is to RTFM. 🙂 

The bug linked above clearly says that that message is shown as a fall back when the directory you provided does not exist and PHP falls back to the system temp dir.

The `/tmp` path only exists on unix systems, so yes, when you misuse the function on Windows, you get the warning. The '@' operator supresses the warning, but you are still misusing the function.

1. The proper solution is to use `tempnam(sys_get_temp_dir(), 'whatever)`.
2. In case where the problem is clearly coming from a 3rd party library, the other solution is to report it and get it fixed upstream (or make your own fork), not changing the (autogenerated!!) vendor directory contents.
