### ISSUE TITLE
More JSX options for formating

### ISSUE THREAD

**Issue by PolGuixe** [Glavin001/atom-beautify#1150]
@prettydiff I know that prettydiff have some options for JSX formatting but atom-beautiy exposes little of them.  

When could we see a version of atom-beautify with all the options of PrettyDiff? 

_Note: currently I am using [React's](https://atom.io/packages/react) reformatting options and it works quite well._

**Comment by prettydiff** [comment]
This request exposes limitations in both Pretty Diff and Atom Beautify.  There are other options open about how to expose more options to various languages/beautifiers.  It has taken me a year to figure out properly for Pretty Diff and there are additional challenges with Atom Beautify.  Here is what I have learned about options:

1. There needs to be a global definition for Options.
    a. That means a globally uniform API to expose.
    b. It also means a single internal code object that can be passed around.
2. Options management needs to be isolated into its own library so that other areas of the application can be extended independently.  The exposed options must adapt and conform to these underlying changes of various beautifiers and parsing libraries so that much of the complexity is hidden from the users and the users just see the simplicity of a single API.
3. There is a lot of manual effort that goes into adding new options and curating them as the underlying code libraries evolve and as feature requests emerge.  This means some additional application work is required to automate this as much as possible.
4. There needs to be a way to process code of one language and then pass off both the proper code and a subset of options to a different library not managed by the same people.  For instance Pretty Diff does not expose a PHP parser, so it would be nice if the outer HTML portion could be beautified by Pretty Diff and then hand off the PHP fragments to an external PHP parser and apply the result back into the code that Pretty Diff is parsing.

I performed item the first above item in Pretty Diff last year, which opened huge opportunities to Pretty Diff.  I only recently accomplished the second item in Pretty Diff and part of the third item.  I am not accomplishing item 4 at all in Pretty Diff, and I have never realized just have big of a gap that is until about a month ago.  These are huge architecture efforts to accomplish that you have no idea you would ever need until requests like this issue emerge.  It has taken me more than a year to realize these necessary fundamental architecture requirements and I clearly still have a lot to learn.

It was a big effort to accomplish this in Pretty Diff as it required a lot of rework.  In Atom Beautify there are additional challenges.  Essentially Atom Beautify is a single point of management solution, a really big universal API between many different beautifiers.  In Pretty Diff I control everything from the API to the parses that consume it, where each of the Pretty Diff parses have been fairly uniform for the past 2 years. Atom Beautify doesn't have that luxury.  It must work to the needs of many different beautifiers.  It is because of this management challenge that Atom Beautify is so popular.

Glavin and I would like to see this project grow beyond Atom.  It is his vision that beautification is a highly desired and necessary quality that should be exposed universally to many different formats and applications.  https://github.com/Glavin001/unibeautify  It would make sense to put this level of rework there, but in the meantime we have to continue to keep the lights on here and maintain this application while also balancing full-time jobs/education and other things.
