### ISSUE TITLE
ERB - <%= %> tag should not break to a new line

### ISSUE THREAD

**Issue by jasonivers** [Glavin001/atom-beautify#1169]
# Description

When beautifying an ERB file, the <%= %> tags should not break to a new line.
# Expected Results

The beautified code should have looked like:

``````
<ul>
  <% 3.times do |x| %>
    <li>This is item <%= x %></li>
  <% end %>
</ul>```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/d0a31ccd2bc9bd02b5a1230e49fd01b0

# Checklist

- [X] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues so I know this is not a duplicate issue
- [X] Generated debugging information and added link for `debug.md` Gist to this issue
``````

**Comment by prettydiff** [comment]
I am looking into this issue and I am not sure I understand the defect.  I believe you are wanting all white space between text and a `<%=` trimmed to a single space character, **but why**?  Is this breaking something?  Should white space between the `<%=` tag and following text also be trimmed to a single space?

Before I proceed with code changes I would like to understand the implications and risks associated with current problem so that I have a better idea of what I am fixing.
