### ISSUE TITLE
Javascript is no longer formatted on save

### ISSUE THREAD

**Issue by KINFOO** [Glavin001/atom-beautify#1260]
# Description

Javascript code is no longer formatted on save.
It used to be.

# Input Before Beautification

This is what the code looked like before:

```js
var works = false;console.log(works?"Works": "Does not work");
```

# Expected Output

The beautified code should have looked like this:

```js
var works = false;
console.log(works ? "Works" : "Does not work");
```

# Actual Output

The beautified code actually looked like this:

```js
var works = false;console.log(works?"Works": "Does not work");
```

# Steps to Reproduce

1. Code in Atom editor
2. Save
3. Code does not get formatted

## Further information

1. When I run command `Atom Beautify: Beautify Editor`
2. Code get formatted wrong
```js
var works = false;
console.log(works
    ? "Works"
    : "Does not work");
```

1. With command line, it is fine
```sh
$ js-beautify /tmp/works.js 
var works = false;
console.log(works ? "Works" : "Does not work");
```

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/anonymous/76fa7263da7f7ff6b71031ba5062a818

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
That is the correct default for Pretty Diff (JSLint compliant).  Pretty Diff has an option to beautify ternary statements onto one line [ternaryline](https://prettydiff.com/documentation.xhtml#ternaryline).  If this option is not supported in Atom Beautify I recommend adding it.

Here is some guidance to get you started:

* https://github.com/Glavin001/atom-beautify/issues/1243
* https://github.com/Glavin001/atom-beautify/issues/524

**Comment by KINFOO** [comment]
Thanks a billion @prettydiff,

My preferences are set to `js-beautify`:

![screenshot_20161011_140923](https://cloud.githubusercontent.com/assets/154818/19269976/d1dd5c14-8fbd-11e6-9d83-af28655e386d.png)

![screenshot_20161011_141027](https://cloud.githubusercontent.com/assets/154818/19269979/d7fc4114-8fbd-11e6-8d8f-cf7d0f19369e.png)

So if `prettydiff` is used when preferences are set to `js-beautify`: it is a bug.

Right?

**Comment by prettydiff** [comment]
There might need to be a different set of options for language *JSX*.  According to your debug.md file Pretty Diff is definitely the beautifier used for grammar *Babel ES6 JavaScript*

**Comment by KINFOO** [comment]
@prettydiff It exists

![screenshot_20161011_162306](https://cloud.githubusercontent.com/assets/154818/19274068/38432af4-8fcf-11e6-98ed-20d141abe964.png)

So when I activate ES6, all JS is handled like ES6?

**Comment by prettydiff** [comment]
These kinds of configuration questions are better answered by @Glavin001

**Comment by Glavin001** [comment]
From https://gist.github.com/anonymous/76fa7263da7f7ff6b71031ba5062a818#original-file-to-be-beautified

> ## Original file to be beautified
>
**Original File Path**: `/home/kevin/Development/works.js`
>
**Original File Grammar**: Babel ES6 JavaScript
>
**Original File Language**: JSX
>
**Language namespace**: jsx
>
**Supported Beautifiers**: Pretty Diff
>
**Selected Beautifier**: Pretty Diff

So this is not being processed as `JavaScript` or `JSON`, it is being treated as `JSX` because the current grammar is `Babel ES6 JavaScript`. See https://github.com/atom/grammar-selector for how to change your editor grammar, if this is incorrect. See https://github.com/Glavin001/atom-beautify/pull/1186#discussion_r79121913 for why `Babel ES6 JavaScript` grammar maps to `JSX` language.

From https://gist.github.com/anonymous/76fa7263da7f7ff6b71031ba5062a818#package-settings

```
"jsx": {
        "indent_size": 4,
        "indent_char": " ",
        "indent_with_tabs": false,
        "preserve_newlines": true,
        "space_in_paren": false,
        "space_after_anon_function": false,
        "break_chained_methods": false,
        "wrap_line_length": 0,
        "end_with_comma": false,
        "disabled": false,
        "default_beautifier": "Pretty Diff",
        "beautify_on_save": false
    },
```

So I recommend you do either of the following:
1) Change the grammar (thus changing the language Atom-Beautify detects)
2) Change `JSX` settings, such as `default_beautifier` and `beautify_on_save`.

Thanks @prettydiff for answer questions before and bringing me in 😃 .
@KINFOO let us know if you still have questions and we can reopen this if needed.
