### ISSUE TITLE
Use a greater-than sign in quotation marks with an error result

### ISSUE THREAD

**Issue by nianqinianyi** [Glavin001/atom-beautify#1269]
# Description

The results of beautification are not what I expect.

# Expected Results

The beautified code should have looked like:

```
import React, {Component} from 'react';
import {Breadcrumb} from 'antd';

class FrameContent extends Component {
    render() {
        return (
            <div className="frame-content">
                <Breadcrumb separator=">">
                    <Breadcrumb.Item>Home</Breadcrumb.Item>
                    <Breadcrumb.Item href="">Application Center</Breadcrumb.Item>
                    <Breadcrumb.Item href="">Application List</Breadcrumb.Item>
                    <Breadcrumb.Item>An Application</Breadcrumb.Item>
                </Breadcrumb>
            </div>
        );
    }
}

export default FrameContent;
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/e44716049dc0a603379fbeab13810630

# Checklist

- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Generated debugging information and added link for `debug.md` Gist to this issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue

**Comment by prettydiff** [comment]
Yeah, this is broken in Pretty Diff v1.16.37 which is the last version published to NPM.  NPM fell out of favor with me.  I am working on an alternative right now at https://github.com/prettydiff/biddle

This is fixed in the current version of Pretty Diff.

**Comment by prettydiff** [comment]
Keeping everybody informed I have fixed biddle.  Check it out now - https://github.com/prettydiff/biddle

I will republish Pretty Diff using biddle in production tomorrow.  I am not ready to give it to Atom Beautify just yet though.  I actually need users to play around with this thing for a bit so that I can get a sense of where the pain points are and just how bad it works for fails for other people.  I wrote a getting started document at https://github.com/prettydiff/biddle/blob/master/documentation/gettingstarted.md

The documentation might be easier to read from the command line though as I included a markdown to CLI parser in biddle.  The number at the end defines the word wrap limit:

    node biddle markdown documentation/gettingstarted.md 80
