### ISSUE TITLE
Not building for Windows

### ISSUE THREAD

**Issue by sentrestage** [Glavin001/atom-beautify#1338]
Will not install to atom on Windows 10. Looking at the plugin documentation page within Atom for atom-beautify it shows that the build is failing for Windows.

**Comment by Glavin001** [comment]
If you look at the [AppVeyor build logs](https://ci.appveyor.com/project/Glavin001/atom-beautify) you'll see the build for Windows is not failing because of Atom-Beautify installation but because of third-party packages, such as `rubocop`, not installing correct. The file https://github.com/Glavin001/atom-beautify/blob/master/appveyor.yml needs to be updated.

While the AppVeyor configuration has not been maintained, because it was proving difficult to manage, you should be able install Atom-Beautify on Windows. If you have specific issues, please describe them and we can reopen this issue.
