### ISSUE TITLE
Beautifying does not error or change PHP code

### ISSUE THREAD

**Issue by Feefty** [Glavin001/atom-beautify#1346]
# Description

It doesn't do anything at all

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. Beautification in Progress but doesn't do anything

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/d18c69435a88ac60c561797cd7d96226

# Checklist

- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Are you getting any kind of PHP errors?

**Comment by Feefty** [comment]
@prettydiff nope,

**Comment by Rexcantor** [comment]
I have the exactly sam issue...

**Comment by WadeShuler** [comment]
Me too. It just spins forever, never times out, doesn't do anything. No error, nothing...

This plugin has given me way more problems than any other Atom plugin!

**Comment by Glavin001** [comment]
@Feefty Looking at your `debug.md` I see:

> 2016-11-11T23:38:15.719Z - debug: [beautifiers\beautifier.coffee] spawn C:\xamppp\php\php.EXE 0=C:\Users\Agatep Family\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.BAT, 1=fix, 2=C:\Users\AGATEP~1\AppData\Local\Temp\temp1161012-10704-1lmox3f.mgz2i0ms4i

I recommend you read my comment to the duplicate issue: https://github.com/Glavin001/atom-beautify/issues/1199#issuecomment-269892599


> This plugin has given me way more problems than any other Atom plugin!

@WadeShuler PHP and/or Windows on Atom-Beautify has given me a ton of trouble, too. All I can say is **the power is yours**. This is what my mentor at work has told me whenever I have an issue. What it means is *you* have the power to solve these issues, because the code is available for you to edit. You have the same access I, or any other developer, does and can therefore contribute. I welcome Pull Requests and please let me know if you have any questions! With hundreds of Issues, @prettydiff and I are *obviously* unable to solve all of the issues. So it is up to **all of you**. I, for one, do not use PHP. So it is extremely unlikely I will be the one to resolve these PHP-CS-Fixer issues each of you are experiencing.

To get you started, here is the applicable code for PHP-CS-Fixer: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/php-cs-fixer.coffee

As I said, please let me know if you have *any* questions! I love to help contributors and without each of us working on the project, it will never improve. It needs love from everyone. Thanks in advance!
