### ISSUE TITLE
Print more helpful error messages for Python

### ISSUE THREAD

**Issue by PanderMusubi** [Glavin001/atom-beautify#1373]
# Description

Beautification did not work out of the box and I had to search for how to fix this.

# Input Before Beautification

n/a

# Expected Output

n/a

# Actual Output

Exception with stack trace.

# Steps to Reproduce

1. Install a system with GNU/Linux system which has APT package manager (Ubuntu or Debian)
2. Add Python 3 code to Atom editor
3. Run command `Atom Beautify: Beautify Editor`
3. Red error box appears on the right side of the screen with exception and stack trace

# Debug

n/a

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

# Solution

Print a message indicating which executable is missing (this can be platform independent). For each platform, offer more precise instruction how to fix. In this case:

Fix this with `sudo apt-get install autopep8` or if that not works `sudo dpkg -P autopep8; sudo pip3 install --upgrade autopep8`

This will greatly speed up getting atom-beautify to work for both new and experienced users.

**Comment by prettydiff** [comment]
Unfortunately those commands are platform specific to POSIX.  They won't do the same things on Windows.  If you wish to take action on this please feel free to submit a pull request.

**Comment by Glavin001** [comment]
The error message should currently include the `help.link` value for the respective beautifier: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/beautifier.coffee#L212-L213

```
See #{help.link} for program \
                            installation instructions.
```

The `help.link` value would be the link to the documentation, such as for autopep8, which includes installation instructions.

However, this has been in place since 2015:
- https://github.com/Glavin001/atom-beautify/blame/master/src/beautifiers/beautifier.coffee#L212-L213
- https://github.com/Glavin001/atom-beautify/blame/master/src/beautifiers/autopep8.coffee#L25

So @PanderMusubi, you should have seen the follow message:

```
See https://github.com/hhatto/autopep8 for program installation instructions.
```

As @prettydiff alluded to, we need to support installation instructions for Mac, Linux, and Windows. The best way we have right now is to refer users to the respective documentation for each beautifier -- which is what we do now.

Please feel free to submit a Pull Request with any improvements you see fit! We are always trying to improve the workflow. Thanks!
