### ISSUE TITLE
Could not find 'uncrustify'. The program may not be installed.

### ISSUE THREAD

**Issue by yujishe** [Glavin001/atom-beautify#1441]
Could not find 'uncrustify'. The program may not be installed.
See http://sourceforge.net/projects/uncrustify/ for program installation instructions.
Your program is properly installed if running 'where.exe uncrustify' in your CMD prompt returns an absolute path to the executable. If this does not work then you have not installed the program correctly and so Atom Beautify will not find the program. Atom Beautify requieautify requires that the program be found in your PATH environment variable. 
Note that this is not an Atom Beautify issue if beautification does not work and the above command also does not work: this is expected behaviour, since you have not properly installed your program. Please properly setup the program and search through existing Atom Beautify issues before creating a new issue. See https://github.com/Glavin001/atom-beautify/search?q=uncrustify&type=Issues for related Issues and https://github.com/Glavin001/atom-beautify/tree/master/docs for documentation. If you are still unable to resolve this issue on your own then please create a new issue and ask for help.
Hide Stack Trace
Error: Could not find 'uncrustify'. The program may not be installed.
    at Uncrustify.module.exports.Beautifier.commandNotFoundError (file:///C:/Users/yu/.atom/packages/atom-beautify-master/src/beautifiers/beautifier.coffee:204:14)
    at file:///C:/Users/yu/.atom/packages/atom-beautify-master/src/beautifiers/beautifier.coffee:304:22
    at tryCatcher (C:\Users\yu\.atom\packages\atom-beautify-master\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\yu\.atom\packages\atom-beautify-master\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\yu\.atom\packages\atom-beautify-master\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\yu\.atom\packages\atom-beautify-master\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\yu\.atom\packages\atom-beautify-master\node_modules\bluebird\js\release\promise.js:687:18)
    at Async._drainQueue (C:\Users\yu\.atom\packages\atom-beautify-master\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\yu\.atom\packages\atom-beautify-master\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Users\yu\.atom\packages\atom-beautify-master\node_modules\bluebird\js\release\async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:

**Comment by yujishe** [comment]
I have already installed.Well, the mouse right button has this menu.but it dosen't working.

**Comment by prettydiff** [comment]
When you type `where.exe uncrustify` in your command prompt what do you get?

**Comment by yujishe** [comment]
This command is used ,and then the tip is used to provide the mode,unable to find the file.
"C:\Users\yu>where.exe uncrustify
信息: 用提供的模式无法找到文件。" 
@prettydiff

**Comment by kaka2634** [comment]
same issue:(

**Comment by Insofan** [comment]
me 2 :(

**Comment by Blizzardo1** [comment]
I can safely say that the build is not passing... furthermore, The PATH env:var has the exe available, as I can execute it through the Command Line.

**Comment by yujishe** [comment]
Are there any sspecific solutions? Or having a corresponding course？

**Comment by nag92** [comment]
Same issue

**Comment by weihanchen** [comment]
Same issue

**Comment by jiangwest** [comment]
I encount the same problem. After trying many times, I give up installing uncrustify in Atom. It is difficult to work right.

**Comment by jiangwest** [comment]
Hi, I find a solution. My OS is windows 7.

- download ` uncrustify-0.64-win32.zip `, which contains `.exe` file
- unzip zip file, and copy it in disk `d`, i.e., `D:\uncrustify-0.64-win32`
- next set environment path, i,e.,`Path = ...; D:\uncrustify-0.64-win32`
- so, OK

I think this problem is caused by windows access authority， it is possible that Windows OS can't permit atom to invoke `.exe` file in Disk C.
I hope you to give better suggestion

**Comment by yujishe** [comment]
Yes, your method is very useful. @jiangwest  
Thanks you ,you suggestion is working.

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.

**Comment by Davey3D** [comment]
Go there and the issue is CLOSED. Something about Dockers. 20+ years in IT and never heard of them. Here's an idea: what about a little program that puts all the files in the right place and makes the necessary config file changes? To make it easy to remember we can call it an 'installer' lol

**Comment by Davey3D** [comment]
Go there and the issue is CLOSED. Something about Dockers. 20+ years in IT and never heard of them. Here's an idea: what about a little program that puts all the files in the right place and makes the necessary config file changes? To make it easy to remember we can call it an 'installer' lol

**Comment by Glavin001** [comment]
> Something about Dockers. 20+ years in IT and never heard of them.

You may find this article helpful: https://www.docker.com/what-docker

> Here's an idea: what about a little program that puts all the files in the right place and makes the necessary config file changes? To make it easy to remember we can call it an 'installer' lol

Feel free to recommend this innovative idea to the Uncrustify maintainers over at https://github.com/uncrustify/uncrustify 

Since installing these third-party beautifiers, such as Uncrustify, is out of scope for Atom-Beautify, it is up to developers like yourself and Uncrustify maintainers to implement the means of getting them installed and supporting Windows, Mac, and Linux. 

This is a great application of Docker so I have integrated it into Atom-Beautify and created https://github.com/Unibeautify/docker-beautifiers such that installation is a way of the past, provided Docker is installed. However, if Docker is too new or unfamiliar of a technology for you, then the conventional manual installation methods (i.e. using an "installer" or otherwise) are always available to you and provided by the third-party beautifier maintainers. Once again, writing these installers is out of scope for Atom-Beautify itself.

**Comment by Davey3D** [comment]
The point was that if it's new to me, it's going to be new to a lot of people. Many are already struggling and frustrated and you're just tossing another layer of confusion and ways for things to go wrong. Was: is it OS, Atom, Atom-Beautify, or Uncrustify. Now:  is it OS, Atom, Atom-Beautify, or Uncrustify ...or Docker or whalebrew or the Docker image or whatever support is required to get this all to work together seamlessly.   

Doesn't matter as I'm one of only 94% of computer users who don't use Mac/Linux. Whalebrew: "Windows support is theoretically possible, but not implemented yet."

I, and many others here, have followed the manual instructions and they don't work reliably. I would suggest that the simplest answer may be to fix the instructions. 

Thanks

**Comment by Glavin001** [comment]
> I, and many others here, have followed the manual instructions and they don't work reliably.

If the manual installation instructions for Uncrustify are insufficient then I encourage you to contribute to https://github.com/uncrustify/uncrustify and improve their documentation. Same goes for Atom-Beautify's automatically generated installation instructions: https://github.com/Glavin001/atom-beautify/blob/master/docs/index.coffee#L207-L226

> Doesn't matter as I'm one of only 94% of computer users who don't use Mac/Linux. Whalebrew: "Windows support is theoretically possible, but not implemented yet."

Whalebrew is not required for Atom-Beautify, only Docker. Whalebrew is optional and a nice-to-have for those who wish to use it. Docker is the requirement, provided the user wishes to try it instead of going the conventional manual installation instructions path.

> Many are already struggling and frustrated and you're just tossing another layer of confusion and ways for things to go wrong. 

Yes, I know many are struggling and there is only so much which can be done.
I propose to you this problem: you need to write a cross-platform (Windows, Mac, Linux) installer which supports multiple types of programs/executables (scripting languages, compiled languages, prebuilt binaries which are architecture specific, etc). To make the problem more concrete, consider Uncrustify: on *some* distributions of Linux you can run `apt-get install uncrustify`, on Mac you can run `brew install uncrustify` (and *only if Homebrew is already installed*), on Windows you can follow the instructions recommended in https://github.com/Glavin001/atom-beautify/issues/772#issuecomment-216685220 . One program (i.e. Uncrustify) and multiple different installation processes. Once again, all of which are out of scope for Atom-Beautify. Atom-Beautify intends to use Uncrustify, not handle its installation.

Let's introduce [Docker](https://docker.com) and see what we can do now. After installing Docker (which has an official "installer" for many Operating Systems) we can simply run `docker pull unibeautify/uncrustify` and utilize the pre-built Docker image generated from https://github.com/Unibeautify/docker-beautifiers . Thus, the cross-platform issue becomes a non-issue. This is why the new Docker layer was added to Atom-Beautify: to target the very problem which leads you to search for this Issue on GitHub in the first place.

Now I understand Docker is new and unfamiliar, and so it is by no means required. However, I trust you can understand -- with a little bit of research -- it's purpose and how it applies in this situation. Also, I hope you understand how building a universal "installer" is non-trivial.
*That being said, if you build such a thing, by all means, please submit a Pull Request, as I would love to improve the installation experience for all users!*

---

In the end, if you have a problem the solution is always to **contribute**. If you do not like the documentation, please submit a Pull Request to improve it. If you do not like having these many layers in place, please feel free to suggest a new idea which meets the growing needs of the users. This is open-source software which I develop in my personal time along with other open-source contributors. We do our best. You have the ability to make changes here, just as we do. Let's work together and improve this.

> I would suggest that the simplest answer may be to fix the instructions.

I agree. I look forward to seeing your Pull Request(s).

**Comment by Davey3D** [comment]
I cannot improve the procedures if i can't get it to work myself. I spent another hour this afternoon googling for solutions online and trying to figure it out myself. 

The Docker website does not list Win7/8 support only win10 so how many hours should I spend trying to get it to work before I find the bug(s) in the Docker non-install are unresolvable OS compatibility issues? 

I've been working with Atom + Platformio + Atom-Beautify + Uncrustify + stm32duino for just a little over a week trying to get it all to work together. Part of that was spent testing new board support for Platformio with one of the developers. Not having seen any of it work at all and not knowing where the boundaries of the products lie, it's a bit challenging to debug it. Once all the obvious errors are gone, i have no good way of telling if it's doing what it's supposed to do or not. Is it a bug or a feature? lol   

And on top of having to actually write working code on a new microcontroller- "is it my code or the dev system or the microcontroller or the external hardware?"

All i want is indents that line up and at the moment doing it by hand is quicker than troubleshooting layers and layers of 'stuff' that even more experienced and knowledgeable people cannot get to work :-( 

Thanks for your efforts

**Comment by Davey3D** [comment]
I looked at Docker. It sounds great for some applications- no argument there. But as a way to get a plug-in installed into a text editor....? I'm not going to install a virtualization environment just for that. I couldn't if I wanted to. They are not planning on supporting Win7/8. "The current version of Docker for Windows runs on 64bit Windows 10 Pro, Enterprise and Education... In the future we will support more versions of Windows 10." Win 10 total is only 25% of the market and I'd guess the great majority of those are Home users. 

 https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install

**Comment by gnkarn** [comment]
this totally confusing , the problem is NOT if it is complicated or simple , the problem is the lack of clarity in my opinion.
How to install the docker image? , almost all beautify images didn't pass the docker build , as stated on the page linked .
So i guess , the first question to be answered is : Is there any Atom - platform Beautifier working ?

Then , in case yes , what is the best step by step procedure to install it , as the normal add-on installation doesn't work .
thank you
