### ISSUE TITLE
How can I fix #1434

### ISSUE THREAD

**Issue by RockWolfHD** [Glavin001/atom-beautify#1470]
You said its a Bug with apm and that it fixed with the newest update but I have the newest and it sill dosent work. Did I can download the fixed files and put them into the right folder?

**Comment by Glavin001** [comment]
I honestly have no idea how to fix these `apm` issues for you. The fix is likely going to be in a future release and I do not know their release date. You should ask them.

In my other comments I recommend everyone experiencing `apm` related issues to ask the team maintaining `apm` for help instead of posting here on Atom-Beautify, since I do not know the inner workings of `apm` I am unqualified to help you. Does that make sense? Have you already created an issue over at https://github.com/atom/apm/issues ? Please feel free to tag me in a comment over there and I'll try to help if the `apm` team has questions which I am able to answer.
