### ISSUE TITLE
Change beautifier used for script tags in .vue files to pretty-diff

### ISSUE THREAD

**Issue by Doeke** [Glavin001/atom-beautify#1602]
Vue-beautifier uses js-beautify for script tags, when I prefer if it used the same beautifier I selected for javascript (pretty-diff). Is there a way to change this?

I keep running into issues because js-beautify, such as line endings being converted to LF (but only inside the script tag, so I end up with mixed line endings in .vue files), and other bugs

**Comment by prettydiff** [comment]
In the Atom Beautify settings you can change the beautifiers associated with a given language.  That way you can make Pretty Diff the beautifier for vue or JS Beautify the beautifier for JavaScript.  I thought JS Beautify was the default for both languages.

**Comment by Glavin001** [comment]
@prettydiff I do not think this is currently customizable for Vue. 

@Doeke pull requests welcome 😃

**Comment by shanemgrey** [comment]
linter-eslint seems to work well, with the added advantage of reading a .eslintrc file so that the fix complies with the linter.  

I'm not sure if the linter-eslint has a hook to work this way, but something like this might work.  I'm confident the scripting here is wrong, but I couldn't figure out how to build to test. 

` 
when "script"
  require("js-beautify")(text, options)
`
to offer the choice of use linter-eslint with something like 
`
when "script"
  switch lang
    when "js-beautify"
      require("js-beautify")(text, options)
    when "linter-eslint"
      require("linter-eslint")(text, options)
    else
      undefined
