### ISSUE TITLE
SCSS breakpoint function are not followed by an empty line

### ISSUE THREAD

**Issue by muuvmuuv** [Glavin001/atom-beautify#1633]
# Description

I'm using the bootstrap `@include media-breakpoint-up(<VP>)` function to style the responsive part. So now when I save my file it deletes the empty line before what is not so good for later viewing.

# Input Before Beautification

This is what the code looked like before:

```
    > iframe,
    video {
      width: 100%;
      height: 100%;
    }

    @include media-breakpoint-up(sm) {
      height: 300px;

      > img {
        width: auto;
        height: 320px;
      }
    }
```

# Expected Output

The beautified code should have looked like this:

```
As above
```

# Actual Output

The beautified code actually looked like this:

```
    > iframe,
    video {
      width: 100%;
      height: 100%;
    }
    @include media-breakpoint-up(sm) {
      height: 300px;

      > img {
        width: auto;
        height: 320px;
      }
    }
```

# Steps to Reproduce

1. Add code to an scss file in Atom editor
2. Save the file

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.

**Comment by prettydiff** [comment]
Please provide a debug.md file or at the very least indicate which beautifier you are using for SCSS in Atom Beautify.

I am going to assume the beautifier is Pretty Diff, because I can reproduce this defect in version 1.16.37, which is the version included in Atom Beautify.  I can not reproduce the defect in the current version of Pretty Diff.  I am working on the final touches this weekend to get independent application distribution/management automation released.  My goal is to have this ready before end of this weekend following completion of these issues:

* https://github.com/prettydiff/biddle/issues/34
* Adding a new update feature to bidddle
* https://github.com/prettydiff/prettydiff/issues/409

**Comment by prettydiff** [comment]
Latest version of Pretty Diff is now in Atom Beautify and so this issue is resolved once the next version of Atom Beautify hits APM.
