### ISSUE TITLE
Could not find 'phpcbf'. The program may not be installed. using WordPress Coding standards

### ISSUE THREAD

**Issue by Vertigoooo** [Glavin001/atom-beautify#1863]
# Description
Hi, as a part of setting up my development environment for WordPress developing, I installed atom-beautify to reformat my code automatically.

I have installed everything correctly according to the instructions at the WordPress coding standards github page: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
with composer which also bundled phpcs and phpcbf and configured everything correctly..

After i went and attempted to configure atom-beautify to use the phpcbf, i get the following Error:

> Could not find 'phpcbf'. The program may not be installed.
> See phpcbf installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://github.com/squizlabs/PHP_CodeSniffer#installation
> You can configure Atom Beautify with the absolute path to 'phpcbf' by setting 'Executable - PHPCBF - Path' in the Atom Beautify package settings.
> Your program is properly installed if running 'where.exe phpcbf' in your CMD prompt returns an absolute path to the executable.

I have added the path to the file to the environmental variable and I have set it under Extensions > phpcbf.
I have also set the phpcbf to be the default coding beautifier and the  WordPress as the standard under PHP section.
I have made sure phpcbf installed correctly by running it from the command prompt (Windows 10)

 

# Input Before Beautification

This is what the code looked like before:

```
<?php
if ( !defined( 'ABSPATH' ) ) exit;

if ( !function_exists( 'hestia_child_parent_css' ) ):
    function hestia_child_parent_css() {
        wp_enqueue_style( 'hestia_child_parent', trailingslashit( get_template_directory_uri() ) . 'style.css', array( 'bootstrap' ) );
    }
endif;
add_action( 'wp_enqueue_scripts', 'hestia_child_parent_css', 10 );
```

# Expected Output

The beautified code should have looked like this:

```
<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
if ( ! function_exists( 'hestia_child_parent_css' ) ) :
	function hestia_child_parent_css() {
		wp_enqueue_style( 'hestia_child_parent', trailingslashit( get_template_directory_uri() ) . 'style.css', array( 'bootstrap' ) );
	}
endif;
add_action( 'wp_enqueue_scripts', 'hestia_child_parent_css', 10 );

```

# Actual Output

did not make any changes

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom and the computer to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues, all of them were about php-cs-fixer and none had the right solution
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.

**Comment by Vertigoooo** [comment]
anyone has some insights?

**Comment by Vertigoooo** [comment]
@szeck87  Well Thank you for making me check that again.. after running debugger tools i managed to understand I was lacking the .bat extension at the end of the path, which i thought was unnecesary..

So for me the solution was to add phpcbf.bat instead of just phpcbf at the end of the path.. only took me 4 days to figure that out :)

**Comment by szeck87** [comment]
Ah, yea for Windows I think you have to.  Sorry I missed that part at the end of your description.

**Comment by meshuu** [comment]
Hi guys, I have the same problem. I'm trying to make Atom Beautify work with WordPress files, because otherwise working on it is unthinkable, but the Atom gives me the same notice it gave to Vertigoooo.

So far the steps I have done are:
- Atom Beautify installation (which works correctly with other formats);
- installation of PHP_CodeSniffer;
- selected as Default Beautifier PHPCBF in Atom Beautify.

Unfortunately I'm a beginner so I do not know if the problem is a missed passage or setting, etc. ..
Can someone help me? Tell me what I can do to make you understand the problem better.
Thank you so much.

**Comment by szeck87** [comment]
@meshuu which way did you [download/install](https://github.com/squizlabs/PHP_CodeSniffer#installation) PHPCBF?

**Comment by szeck87** [comment]
@meshuu those two files you curl'ed should be somewhere on your Mac now, depending on which directory you were in when you did so.  Copy the path to the `phpcbf.phar` file and paste it into Atom Beautify's settings.  It would be under `Executables -> PHPCBF -> Binary/Script Path`.  Try using Atom Beautify against a PHP file after doing that.

**Comment by meshuu** [comment]
I did as you suggested:
![screen](https://user-images.githubusercontent.com/37701762/39488570-06d7a62a-4d83-11e8-899a-716d4976bf40.png)
but the program still gives me the same error.
Maybe something is still missing?

**Comment by szeck87** [comment]
Looks like you are still in the wrong spot.  Under settings, there is an Executables heading just below General.
![screen shot 2018-05-01 at 2 23 14 pm](https://user-images.githubusercontent.com/8315038/39489446-387f1560-4d4b-11e8-9893-55f041ebd27f.png)

Under that is PHPCBF where you want to put that path.  Also I don't think you need the `~` at the beginning, and should be `.phar` at the end, without the `y`.

Make sure it's the full path to phar file and that both phar files you downloaded are in the same directory.

**Comment by meshuu** [comment]
You're right, I realized after making the screen that there were errors in the syntax. I proceeded to correct and I entered the path in the right field.
The previous error message no longer appears, but another one appears:
![schermata 2018-05-02 alle 08 42 02](https://user-images.githubusercontent.com/37701762/39509083-37c48b4c-4de5-11e8-881a-cea55c8c8986.png)
As you suggested, this file is also in the same folder as the file: "phpcs.phar".
However @ szeck87 thanks again for your interest, I'm grateful. I hope we can solve.

**Comment by szeck87** [comment]
@meshuu please run the debug command in Atom for Atom Beautify.  See here for instructions:  https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist.  Paste the link to the gist here in this issue.

**Comment by meshuu** [comment]
@szeck87 Here is the link: https://gist.github.com/meshuu/633921ba8793287a22aa32821682c433

**Comment by szeck87** [comment]
@meshuu please do the debug command against a php file.

**Comment by meshuu** [comment]
@szeck87 I corrected the gist.

**Comment by szeck87** [comment]
Hmm, looks like it is running only the `/path/to/file/phpcbf.phar` file when it should be running `php /path/to/file/phpcbf.phar`.  Likely due to an update to phpcbf that was never accounted for by atom-beautify.

Since you're on a Mac, I would recommend just using the Homebrew version.  If you don't have Homebrew installed, directions are here:  https://brew.sh/.  Then run `brew install php-code-sniffer`.  Remove whatever you pasted into the path in Atom Beautify settings and it should work after all that.

**Comment by meshuu** [comment]
@szeck87 I cleaned up all the paths and installed php-code-sniffer via Brew.
Everything seems to be successful because when I try to perform the beautification no error message appears, but not after the appearance of the analysis pop-up nothing happens, so it does not perform any beautification.
Around I read that you need other tools to make the beautification of a WordPress file, like WordPress-Coding-Standards that I do not understand how to install.
So it may depend on the fact that essential packages are missing that I have not installed?
Also when opening a WordPress file this is not recognized as such, at least it would seem from here:
![schermata 2018-05-03 alle 10 15 06](https://user-images.githubusercontent.com/37701762/39566147-dfc5ef9a-4eba-11e8-95d2-11b3c6c2baaa.png)
However I did not think it was so complicated to make the beaufication work with a WordPress file.

**Comment by nelson6e65** [comment]
Hi. How can I use the local bin installed by Composer in my project as dependency instead of a global bin path?
