### ISSUE TITLE
PHP: Remove ending tag

### ISSUE THREAD

**Issue by burhandodhy** [Glavin001/atom-beautify#2104]
# Description

When I run beautify it removes the PHP ending tag from the file 

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
<?php

echo 'Test';

?>

```

# Expected Output

The beautified code should have looked like this:

```
<?php

echo 'Test';

?>

```

# Actual Output

The beautified code actually looked like this:

```
<?php

echo 'Test';


```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.

**Comment by szeck87** [comment]
In this example it's not necessary to have a closing tag, so it removes it.  Relevant PHP doc:  http://php.net/basic-syntax.instruction-separation.

By default PHP-CS-Fixer has a rule, no_closing_tag, that does this.  If you're using a config file, you can remove that rule and it won't remove the ending block.  Otherwise you would need to put the rules you do want in the settings (Packages -> Atom Beautify -> Settings -> Expand PHP and the second to last option is `rules`.  Put what rules you want in there.

**Comment by szeck87** [comment]
You can put any rule(s) into the settings, but only those rules will be applied when formatting.  If you put in no_empty_comment, only that rule will be applied, so in that case no_closing_tag will not.  But I doubt that's what you want sine it also would not apply any other rules.

I would look over [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) documentation for how to configure it the way you want.
