### ISSUE TITLE
Support request:  Nette and its latte template engine

### ISSUE THREAD

**Issue by TomasSestak** [Glavin001/atom-beautify#2225]
https://nette.org/en/
https://latte.nette.org/

xoxo

**Comment by prkwcz** [comment]
I would highly appreciate a support of especially [Latte-Templates](https://latte.nette.org/en/) (which is in my opinion a subset of HTML).
In the past, Files with the ending latte were often assigned as HTML and the beautification worked quite well.

Now I installed the package [language-latte](https://atom.io/packages/language-latte) which highlights the syntax quite well but the disadvantage is that Ibeautification is chrashing now. 
Would be good if you could support in that respect.

**Comment by prettydiff** [comment]
Latte seems like it would be super simple to add support for, but right now I am way backed up with other issues.  Here is how this would work.

1. Add syntax support for the Latte grammar to the markup.ts lexer file of https://github.com/unibeautify/parse-framework
2. Add tests files
3. The next time I update Pretty Diff support is likely automatic because the conventions around markup all pretty orderly now.

I just recently publish my beautifier to the next major version and am busy closing out defects I wish I had discovered earlier.  Once I am done with this.  I have other requests to work out and I need to assist with integrating Pretty Diff into Unibeautify (this project's successor).  While I am doing all of that I have a bunch of tasks queued up for the next major version of the parser and I sorely need to revise the diff algorithm that makes Pretty Diff a bit smarter.  It works great the way most people use diffs in a CVS, but it is failing on more intelligent things.
