### ISSUE TITLE
Apply filter to list of files before `Beautify Directory`

### ISSUE THREAD

**Issue by WebFreak001** [Glavin001/atom-beautify#224]
I accidentally pressed format everything and then all my .min.js files got formatted (like jquery) and now my project is by far bigger. Would be nice if there would be a filter in the config for ignoring certain files.

**Comment by Glavin001** [comment]
Good idea.

**Comment by KillerJK** [comment]
I would like to add that the list of ignored files/patterns should always be used, regardless of how you run atom-beautify. For example, I'm running csscomb when I save my .scss files. It works fine, but mixins/functions are also reordered, and sometimes they break.

Csscomb has an option to exclude certain patterns in its config file, but because atom-beautify is calling processString() instead of processFile(), the exclude list is not being used.

I want to submit pull requests to both projects to fix this particular case, but it would be great if atom-beautify had this feature. Other tools may not have the option to exclude any files. I guess you are not expected to edit files that are minified, so they should never be beautified/deminified when saving them.

However, csscomb is a special case. In addition to beautifying, it also reorders the file itself, hence the need to make it ignore certain (but not all) files that contain logic. Sometimes they have logic and must be left alone, and others are still mixins but have no logic, so reordering them can be desirable.

**Comment by whmountains** [comment]
This would be really nice to have!
