### ISSUE TITLE
"In" Containment Operator in Twig

### ISSUE THREAD

**Issue by pgraber** [Glavin001/atom-beautify#2295]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

```
  {% if label_display in ['before', 'invisible'] %}
    <div class="col-4-md">
      {{ label }}
    </div>
  {% endif %}

```

# Expected Output

The beautified code should have looked like this:

```
  {% if label_display in ['before', 'invisible'] %}
    <div class="col-4-md">
      {{ label }}
    </div>
  {% endif %}


```

# Actual Output

The beautified code actually looked like this:

Deleting space after In operator.  Causing Twig snytax errors.

```

  {% if label_display in['before', 'invisible'] %}
    <div class="col-4-md">
      {{ label }}
    </div>
  {% endif %}

```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Check which beautifier you are using internally within Atom Beautify.  I believe, though I could be wrong, that Pretty Diff is the default beautifier for Twig.  If this is a Pretty Diff defect please assist us with getting the latest major version of Pretty Diff into Unibeautify (Atom Beautify's successor) since this defect is no longer present in Pretty Diff: https://github.com/Unibeautify/beautifier-prettydiff/issues/114

If the defect is the result of a different beautifier please open an issue with the other beautifier.
