### ISSUE TITLE
How to install PHP-CS Fixer using Docker?

### ISSUE THREAD

**Issue by AVetvinij** [Glavin001/atom-beautify#2343]
# Description

My PHP path is in C:\xampp\php and I chose to install using Docker.
How to make PHP (PHP-CS-fixer) beautify works?
![er](https://user-images.githubusercontent.com/32244467/56656291-5279a000-66bf-11e9-9f6a-f5fd4d3dd26e.PNG)

**Comment by loelkes** [comment]
Since I was stuck at the same point, came here and didn't find and answer, here's what I did:

Place the following executable script in your `$PATH` (e.g. `/usr/local/bin`)
```
#!/bin/bash
docker run -it --user "$(id -u):$(id -g)" -v "$(pwd)":/workdir -w /workdir unibeautify/php-cs-fixer "$@"
```

You can now run `php-cs-fixer`.

EDIT: Be careful where you run it since it will mount the current directory in the docker container even if you only do `php-cs-fixer -v` or similar. This can cause performance issues in large directories such as `$HOME`.
