### ISSUE TITLE
`Beautify Editor` command should come first in command palette list

### ISSUE THREAD

**Issue by framerate** [Glavin001/atom-beautify#240]
Love this plugin. My workflow is usually:

command + shift + p ---> type "beaut" ---> hit enter.

The new version added a "debug" command that is at the top of the auto complete list and it causes me to hit it all the time.

I don't know the origin of the debug command, but would it be possible to at least order it at the bottom so it doesn't accidentally fire?

**Comment by Glavin001** [comment]
> I don't know the origin of the debug command,

See #237 and #236.

> My workflow is usually:
> command + shift + p ---> type "beaut" ---> hit enter.

I recommend using a keyboard shortcut for `beautify:beautify-editor`.

> The new version added a "debug" command that is at the top of the auto complete list and it causes me to hit it all the time.
> ...
> would it be possible to at least order it at the bottom so it doesn't accidentally fire?

I am not entirely sure why it would appear first (`b` in `beautify editor` comes before `d` in `debug` last time I checked), however I would also like to see `beautify editor` appear first in that list, so if you figure out why it is ordering that way and how to change it, please let me know.

**Comment by ponychicken** [comment]
That annoys me a lot. I don't use beautify enough to remember the keyboard shortcut and now I frequently hit this debug thing.

**Comment by Glavin001** [comment]
> That annoys me a lot.

Me, too.

> now I frequently hit this debug thing ...
> ... this feels like a regression in usability to me

The *addition* of the **Debug** command is an excellent feature with many advantages, given the large quantity of Issues created and the severe lack of quality in debugging information provided by users to allow me to resolve them.

However, I do see your use case, and while it is a little "bug", and not even Atom Beautify's fault -- it is caused by how Atom orders the commands, see https://github.com/atom/command-palette/issues/2#issuecomment-36475047 and https://github.com/atom/command-palette/issues/28 and https://github.com/atom/fuzzaldrin -- I will attempt to find a solution for you, since you are resistant to the common practice of using keyboard shortcuts.

**Comment by Glavin001** [comment]
Published fix to v0.22.4

Please check and let me know it works for you.

**Comment by framerate** [comment]
Looks great! I had to restart atom to see it, so make sure you do that if you’re verifying!




Thanks so much!

**Comment by Glavin001** [comment]
> I had to restart atom to see it

Yeah, updating packages in Atom rarely works well. I make it a habit of *always* restarting Atom after any package changes.

> Thanks so much!

You're welcome! Let me know if there's anything else.

**Comment by ponychicken** [comment]
Fantastic, that did the trick for me.
