### ISSUE TITLE
PHP beautifcation support

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#26]
See https://github.com/sdwood/php-beautifier and https://github.com/SublimeText/PhpBeautifier and http://pear.php.net/package/PHP_Beautifier

**Comment by batmandakh** [comment]
I can't use php_beautifier cause of temporary file of current active session... I'm on Ubuntu 14.04 with php 5.6 and latest version of atom. All php_beautifier dependencies have installed and they're working correctly from terminal.
Please see giving error:

Command failed: /bin/sh -c [ -f ~/.bash_profile ] && source ~/.bash_profile;[ -f ~/.bashrc ] && source ~/.bashrc;php "/usr/bin/php_beautifier " --input "/tmp/input115014-12433-1i2xoqb" --output "/tmp/115014-12433-1ke9sic" /bin/sh: 1: source: not found

I've watched carefully "/tmp/" directory. But there's no file created during any session... How to solve this?

**Comment by jaoued** [comment]
@Batmandakh I have he same error.

**Comment by jclappiway** [comment]
+1 same error with tmp files

**Comment by Glavin001** [comment]
Sounds like for some reason `source ~/.bashrc;` is not working on your Ubuntu computer.

The afflicting lines of code can be found at: https://github.com/Glavin001/atom-beautify/blob/master/lib/langs/cli-beautify.coffee#L45-L50

If you can comment out those lines in your local installation of Atom Beautify, that should fix it. You will have to manually set the path of `php_beautifier` in the Atom Beautify Package Settings.

#164 will solve this.

**Comment by john-d-pelingo** [comment]
Whenever I try to use your package to beautify my php file it throws me this.


----------------------------------------------------
spawn php ENOENT
spawn php ENOENT
Hide Stack Trace
Error: spawn php ENOENT
  at exports._errnoException (util.js:734:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
  at child_process.js:1127:20
  at process._tickCallback (node.js:357:13)
----------------------------------------------------

Is it because of wrong configuration?
