### ISSUE TITLE
add tidy-markdown support

### ISSUE THREAD

**Issue by slang800** [Glavin001/atom-beautify#292]
> If you want to get rid of the pandoc dep, I wrote a markdown beautifier in pure JS: https://github.com/slang800/tidy-markdown (so it can be required via npm)

**Comment by Glavin001** [comment]
I have added support / switched to tidy-markdown for the next release of Atom Beautify (see #282 ).
However I will not be able to release with tidy-markdown yet because there are a couple bugs / missing features (see https://github.com/slang800/tidy-markdown/issues/7 and https://github.com/slang800/tidy-markdown/issues/8) that will break Atom Beautify's Markdown backwards compatibility (tidy-markdown is not *yet* equal to and therefore cannot be substituted for Pandoc).
That being said, I am very pleased with tidy-markdown and it is definitely a better solution than using Pandoc. Once these two Issues above are taken care of then we are all set to release! Thank you for the great work so far!

**Comment by Glavin001** [comment]
Published to v0.25.0

This is a very big release with lots of internal changes and (hopefully) no breaking changes. Please let me know if you are experiencing any unusual behaviour / breaking changes after updating. Thank you.
