### ISSUE TITLE
Lazy load beautifier dependencies

### ISSUE THREAD

**Issue by andya9** [Glavin001/atom-beautify#320]
As atom-beautify is enormous (50M installed!), maybe it would be good to split it into modules, as linter packages does, so that users can choose what languages to enable.

**Comment by Glavin001** [comment]
I want Atom Beautify to be the one-stop place for all code beautification in Atom. As of #282, each beautifier is very light-weight itself (e.g. https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/autopep8.coffee ) and it'd be annoying for me to maintain at least (currently) 15 small repos for each beautifier, when right now they are simply files. So I am not supportive of splitting into separate modules, as the linter package does.

However, I do understand your concern with loading all of these dependencies at install time. I was thinking of using [lazy-require](https://www.npmjs.com/package/lazy-require) such that the first time a user would use a particular beautifier it would *then* require all of it's dependencies, instead of up front. Thus, installation of Atom Beautify would be very quick, and then the first time a user would beautify a file, it would then automatically install whatever dependencies it needs for that beautifier.

Essentially, I picture it as Atom Beautify being able to recognize each language it supports and then effectively install each module upon usage. Like linter package, except auto-installing: you do not need to install linter and then linter-coffeescript, you simply install linter and try to lint CoffeeScript and it will detect that it is supported and install it for you.

**Comment by andya9** [comment]
Yes, I was concerned with the size of dependencies, not of the beautifiers. I like your idea of autoinstalling when used; thank’you very much for considering this!

**Comment by Glavin001** [comment]
Currently `node_modules` directory is about 74.3 MB. I would like to dramatically cut this down.
However, do note that users that use the bigger packages -- `typescript-formatter`, `jscs`, `prettydiff`, `gherkin` -- will of course increase their `node_module` contents. The point being that updating Atom Beautify will be very quick and you will only install what you need as you need it based on your usage.

**Comment by Glavin001** [comment]
Atom-Beautify will be migrating to Unibeautify ( #1174 ) which will support beautifiers that are separated from the core ( #620 ) and therefore dramatically reducing file size and installation time. No more unwanted beautifiers! Only install what you need.

I am closing this issue in favour of following #1174 .
