### ISSUE TITLE
Add indentation option to Ruby

### ISSUE THREAD

**Issue by THPubs** [Glavin001/atom-beautify#341]
All my projects are done with 4 spaces. But when beautified it convert the indentation to 2. How can I change this?

**Comment by Glavin001** [comment]
> All my projects are done with 4 spaces. But when beautified it convert the indentation to 2.

That must be default for either Rubocop or Ruby Beautify.

Currently neither of the Ruby beautifiers supports any configurable options:
- Rubocop: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/rubocop.coffee#L16-L18
- Ruby Beautify: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/ruby-beautify.coffee#L17-L19

> How can I change this?

A Pull Request that adds support would be ideal, since support currently does not exist.

### How to add options to a language and beautifier

1) Language Options would be added at https://github.com/Glavin001/atom-beautify/blob/master/src/languages/ruby.coffee#L21
See https://github.com/Glavin001/atom-beautify/blob/master/src/languages/javascript.coffee#L30-L106 for example.
2) You could leave it as `true` (all options supported) or specify supported options directly: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/rubocop.coffee#L12
3) Change the Command-Line Interface arguments of Rubocop to support those new options: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/rubocop.coffee#L17-L18
For example: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/autopep8.coffee#L19-L22

**Comment by THPubs** [comment]
Temporarily fixed it by adding `.rubocop.yml` in the home folder and adding the following configuration option :

     Style/IndentationWidth:
         Width: 4
But it would be better if we can set it from the plugin settings.
One more thing, it would be better if we can override indentation value to all languages by one global value.

**Comment by Glavin001** [comment]
> But it would be better if we can set it from the plugin settings.

Agreed. This will be available once this issue is implemented.

> One more thing, it would be better if we can override indentation value to all languages by one global value.

With #346 implemented and published, I have added a `_default` key that should work for `.jsbeautifyrc` files. Like CSS, Atom Beautify's options are prioritized by specificity: the options set closer to the file itself, or for that specific language, take precedence.

For instance, you could have Atom Beautify package settings setup for your personal configuration, however when working on a project with others your settings may be different. The `.jsbeautifyrc` file takes precedence over the package settings and Atom editor settings, etc. Furthermore, you could have multiple `.jsbeautifyrc` files, potentially in the same directory as your current file and all the way up to root  directory. All of these would be applied, with priority going to the closest file to your currently beautified file.

So if you want to override indentation value for all languages with one global value, you could do so by creating a `.jsbeautifyrc` file with `_default` key namespace and set your configuration there, which should override for other languages.

Let me know if that works. Open another issue if you have any problems / questions.

**Comment by THPubs** [comment]
Great thanks! :-)

**Comment by Glavin001** [comment]
Published to v0.28.2

**Comment by THPubs** [comment]
@Glavin001 Thanks a lot! Im confirming that it works :-)
