### ISSUE TITLE
Please add support for ColdFusion

### ISSUE THREAD

**Issue by yrsengar** [Glavin001/atom-beautify#354]

**Comment by Glavin001** [comment]
This? http://en.wikipedia.org/wiki/ColdFusion_Markup_Language#Syntax

**Comment by prettydiff** [comment]
It has been over a decade since I have worked with Cold Fusion, but I remember the language is really 3 languages:

* CFScript
* CFML
* something else that I don't remember (maybe something that looks like C++ or Java)

Each of those are wildly different. CFScript resembles JavaScript syntax but uses more Java like grammars. CFML resembles XML.  @yrsengar try to enter a bunch of input into the Pretty Diff tool and really see if your input can get the tool to produce corrupt output.

**Comment by abramadams** [comment]
Would be nice to have CFScript support.  Modern CFML script looks more like this: https://github.com/adamcameron/cfscript/blob/master/cfscript.md

With CFML tags reserved for view templates.  

I've tested a few script CFC files on prettydiff and it seems to do a decent job.

**Comment by prettydiff** [comment]
CFML script looks like JavaScript except I noticed some operators, such as `?:` that JavaScript does not have.  My concern there is that my JavaScript parser is extremely JavaScript centric and while it may sometimes do an arguably decent job of parsing any language C looking language ever language has a unique grammar.

Would you be able to post a gist of a CFC file so that I could see what it looks like.  I don't want you to get excited that Pretty Diff could solve your problems when in fact it may be corrupting your code.

**Comment by abramadams** [comment]
Here are a few examples:
https://github.com/abramadams/wkhtml/blob/master/com/wkhtml/pdf.cfc
https://github.com/framework-one/fw1/blob/master/framework/one.cfc
https://github.com/Ortus-Solutions/commandbox/blob/master/src/cfml/system/services/ServerService.cfc

Thanks! (not that I'm excited.. just hopeful :)

**Comment by prettydiff** [comment]
My JavaScript parser is handling that code more accurately than I imagined.  I still do not feel confident to provide official support with my tool merely because I do not write in that language and I don't know what the potential error cases are.

I am willing to provide bug fixes and fulfill requests as they come along though.  Since I am not willing ColdFusion, but am willing to offer to unofficially offer assistance please change the settings in atom-beautify to allow Pretty Diff as the beautifier for ColdFusion on your local computer.  As you encounter problems open an issue on Github and I will examine the problem.

@Glavin001 can likely provide instructions on how to extend the settings to use Pretty Diff as your ColdFusion beautifier.

**Comment by abramadams** [comment]
@prettydiff thanks for the update!  I'll try that locally, only not sure how to.  @Glavin001, I'd be forever grateful if you could provide instructions to extend the settings to use Pretty Diff for ColdFusion.

**Comment by Glavin001** [comment]
For @abramadams : Steps to add ColdFusion language and use Pretty Diff as default beautifier.

1. Add Language `ColdFusion` to Atom Beautify. Read `How to add a Language` in https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md#how-to-add-a-language for details. 
2. Add `ColdFusion` support to `Pretty Diff` beautifier. See https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L30 for beautifier's code. You can simply add `ColdFusion: true` and Atom Beautify will see that the Pretty Diff beautifier supports that language.
3. Determine which language performs best for ColdFusion using Pretty Diff. Go to http://prettydiff.com/ and play around with `Auto detect default` options. Remember which Pretty Diff supported language works best.
4. Properly handle the ColdFusion language and select the best Pretty Diff language to use. Go to https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L57-L91 and add the language that you found worked best on http://prettydiff.com/ 
5. Read [`How to add a Beautifier for a Language` step 4](https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md#how-to-add-a-beautifier-for-a-language) for instructions on how to add test files. I insist that a simple test be added for a Pull Request to be merged :wink:.

Let me know if you have any questions :smile:. Thank you!

**Comment by finalcut** [comment]
I just want to chime in that none of the beautifiers that exist really work well with coldfusion. 
The presence of optional end tags tends to really mess things up.

**Comment by Glavin001** [comment]
Thanks for your feedback @finalcut . I recommend also following up with this issue on Pretty Diff: https://github.com/Glavin001/atom-beautify/issues/526

**Comment by finalcut** [comment]
Thanks for the pointer @Glavin001  - it appears he has moved the actual work of implementation to Pretty Diff: [#158](https://github.com/prettydiff/prettydiff/issues/158)  The issue you linked to is directly related to Atom support.

**Comment by Glavin001** [comment]
Oops. Good eye. Thanks for catching that.

**Comment by prettydiff** [comment]
I have published support for ColdFusion with version 1.16.1.

**Comment by Glavin001** [comment]
@prettydiff not sure if Atom Beautify will support it, yet. What [`lang`](https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L64-L97) would it be for Pretty Diff to beautify ColdFusion?

I think a Pull Request would need to be made, after reading over https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md
Or the user could switch their file grammar in Atom.

**Comment by prettydiff** [comment]
It would just be HTML to Pretty Diff.

**Comment by finalcut** [comment]
is there anything I can do to help get this integrated/updated?

**Comment by prettydiff** [comment]
Yeah, actually, Glavin is really busy right now with school finals and some end of year projects at work.  If you add the support for the coldfusion file extensions and submit a pull request I am sure he would be happy to review it and merge it.

There are some pages in the wiki that might help like this one: https://github.com/Glavin001/atom-beautify/wiki/Add-an-unsupported-language-using-an-existing-beautifier

**Comment by Glavin001** [comment]
@finalcut : Yup, I'd recommend reading https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md and add support for ColdFusion to Pretty Diff's beautifier at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee

--

**Update**: Wow, @prettydiff is on the ball. Thanks! :smile:

**Comment by finalcut** [comment]
Im working on the pull request now.  Thanks

**Comment by billrawlinson** [comment]
just curious what the status of this is at this point thanks.

**Comment by Glavin001** [comment]
Closed by #717. Published to v0.28.23
