### ISSUE TITLE
esnext bug: incorrect beautification of statements of form: import { foo } from "module";

### ISSUE THREAD

**Issue by breathe** [Glavin001/atom-beautify#362]
Turns this:

```
import { Navigation} from 'react-router';
```

into this:

```
import {
  Navigation
}
from 'react-router';
```

Bug or problem with my configuration??  Thanks

**Comment by prettydiff** [comment]
ESNext was a transpiler that merged with Babel. As such I would assume this to be JavaScript, but if not then what language should this be?

**Comment by breathe** [comment]
Sorry I was using esnext because I can't keep the name straight regarding es6/es7/es2015/etc... (unclear to me what name is most used).  This is es6 module syntax supported by babel transpiler -- beautifier formats it in a very strange way ...

**Comment by prettydiff** [comment]
atom-beautify uses jsBeautify for its JavaScript beautification, so you might want to open a bug there: https://github.com/beautify-web/js-beautify

I will be updating this in my own application as well.

**Comment by Glavin001** [comment]
@prettydiff is right on.

---

`Pretty Diff` beautifier is able to be selected instead of `JS Beautify` if you prefer. Go to Atom package settings panel -> `Atom Beautify` -> `Language Config - JavaScript - Default Beautifier` -> select the beautifier you wish, such as `Pretty Diff`, if it works better.

Also, if either Pretty Diff or JS Beautify is updated, you can simply uninstall and reinstall Atom Beautify and it will cause Atom to update to the latest dependencies, since my dependency rules are intentionally not strict: https://github.com/Glavin001/atom-beautify/blob/master/package.json#L65 

Hope that helps.

**Comment by prettydiff** [comment]
@breathe What if the code looks like this:

    import {
        square, diag
    } from 'lib';

Technically any curly brace represents a block.  From looking at the ES6 code examples it appears a diversity of code can be parsed to determine the import items.  This second code sample seems valid:

    import _, {
        named1 as myNamed1[0], named2
    } from 'src/mylib';

**Comment by Glavin001** [comment]
I am going to close this Atom Beautify issue and let it continue on Pretty Diff's repo.

When this is resolved on Pretty Diff, let me know and I can update the dependency.

As a temporary fix, to force Atom Beautify to update to the latest Pretty Diff, you can simply uninstall and reinstall Atom Beautify and Atom will install the latest Pretty Diff.

**Comment by StevenRoan** [comment]
@Glavin001  it seems that the [issue](https://github.com/prettydiff/prettydiff/issues/101) is fixed. Could we have this option now? Thanks!
