### ISSUE TITLE
Support for custom beautifier command (based on grammar)

### ISSUE THREAD

**Issue by kankaristo** [Glavin001/atom-beautify#388]
Thanks for a great package, beautifying on every save is fantastic! :)

It would be great to be able to specify a custom command per grammar.

I recently moved to Uncrustify (so that I could use this package), and found that it's a little bit better then Artistic Style. But, it's missing a [critical feature](https://github.com/bengardner/uncrustify/issues/132) (for me anyway), so I wrote a little wrapper script, which runs after Uncrustify.

I would also like to use a slightly different config file for headers and definition files, which would be easy to do in a custom script.

It would be great to be able to specify a custom command to run for a specified grammar. These could be specified in a CSON file:
```cson
{
  # Grammar
  "cpp": {
    # Beautifier command, simple regex for replacing parameters
    "command": "uncrustify.sh -c {config_file} -f {input_file} > {output_file}"
    
    # Alternatively (a bit more complex):
    "command": "uncrustify.sh -c {config_file} -f {input_file}"
    "input-from-stdin": false
    "outputs-to-stdout": true
    
    # Other possible variables to replace (the above 3 will go a long way)
    #{project_path}
    #{grammar}
  }
  
  # Other grammars
  #...
}
```

This would essentially allow for any beautifier to be used. `atom-beautify` would handle calling the command when appropriate, finding the config file, replacing the buffer contents, handling errors (return values and stderr), etc.

The CSON file could be project specific, which would allow for per-project beautifying commands.

**Comment by Glavin001** [comment]
I am not in support of allowing a raw custom command for each beautifier. Generating the command should be handled as it is now by Atom Beautify internally. All customization should be handled with options and Atom Beautify should generate the appropriate command.

> I would also like to use a slightly different config file for headers and definition files, which would be easy to do in a custom script.

However, I understand your desire to use different config files for the grammars or extensions of an Atom Beautify supported language. If you submit a pull request enhancing the customization of the Uncrustify beautifier, I will review it.

Some pointers: 
- Here is the C++ language file: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/cpp.coffee
- Add more [`options`](https://github.com/Glavin001/atom-beautify/blob/master/src/languages/cpp.coffee#L29) that could be applied in the [Uncrustify beautifier](https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/uncrustify/index.coffee#L25-L27)
- Get the active Text Editor and use it to get filename or extract filename's extension or grammar: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/uncrustify/index.coffee#L35
- Handle the `language` and `options` and generate the `command` you want: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/uncrustify/index.coffee#L49-L77 

I'd recommend adding option(s) for mapping different grammars or extensions to different config files.

```javascript
{
  // Atom Beautify language namespace for language C++
  "cpp": {
    // new option for handling multiple config files
    "configMap": {
     // using file's extension
      ".h": "config_file_1",
      ".cpp": "config_file_2"
    }
  }
}
```

I hope that helps.

Since this issue is actually regarding allowing a "custom command per grammar" and I am not in support of that, I am going to close this issue. If you really want to have a custom command per grammar, then I suppose you could fork this repository and implement it on your own. You could even submit a pull request for that, however I think it is unlikely I will be merging something like that.

Please feel free to create a new issue for the Uncrustify beautifier enhancements as described above, that should satisfy your needs, and submit the Pull Request to be reviewed and merged. Thanks.

**Comment by kankaristo** [comment]
The biggest problem with doing it that way is that it's "per user" and not "per project". Beautifying should always be on a per project basis, and not all projects use the same beautifier or options.

Having the CSON file in the project's directory would allow for both custom settings and a custom command for that project. The command may even be completely custom to that project (like my post-Uncrustify script, which does something that Uncrustify doesn't support).

IMO, it would also be easier to extend and easier to use for non-Atom users. All you need is the beautifier's config file and the command to run, `atom-beautify` would just automate.

But I realize that it might mean a major rewrite and that opinions differ. Thanks for your reply! :)

**Comment by Glavin001** [comment]
> The biggest problem with doing it that way is that it's "per user" and not "per project". Beautifying should always be on a per project basis, and not all projects use the same beautifier or options.

I agree it should be on a per project basis, and it is. Options can go in the `.jsbeautifyrc` config file and persist between projects. The Atom Beautify package settings would be a global and per user, and it's up to users to choose the appropriate medium to persist their configurations.

> IMO, it would also be easier to extend and easier to use for non-Atom users. All you need is the beautifier's config file and the command to run, atom-beautify would just automate.

Automating beautification based on a config file is what Atom Beautify aims to do and does now. Also, I am not sure how non-Atom users are applicable.
The options for Atom Beautify, such as extracted from `.jsbeautifyrc` (which will be renamed later, #41 ), provide customization and the internal beautifiers of Atom Beautify should make it easy and allow users to support reusable use cases, so long as they make sense.

In your alternative, complex example provided you had

>```
    "input-from-stdin": false
    "outputs-to-stdout": true
```

which would definitely need to be supported and adds complexity that now users will have to think about. This is currently abstracted by Atom Beautify, such that some beautifiers are Node packages, others are CLI beautifiers that use stdin, stdout, edit the file in place, or edit an output file after reading from a separate input file. Depending on the beautifier, more complexities are handled transparently. These cases should not be in the configuration file, per project, and definitely should not be handled by the user. 

What I am essentially saying is, take your logic that you want to have customization commands for, and make options to allow Atom Beautify to generate each of those cases, along with handling the existing cases that Atom Beautify already handles.
