### ISSUE TITLE
Need more Enhancement in XML Beautify

### ISSUE THREAD

**Issue by shanalikhan1** [Glavin001/atom-beautify#389]
Hi , 
Im currently using Altova XML Spy for XML purpose. it beautifies the XML very well.
Its my suggesstion to kindly have a check the difference between your package and them. 
It would be a nice to have such feature in your package.
what it should be : 
![expected](https://cloud.githubusercontent.com/assets/8774556/8032208/cb4762da-0ded-11e5-9e14-1401782931cc.png)
Currently XML beautify :
![current](https://cloud.githubusercontent.com/assets/8774556/8032201/c544b50e-0ded-11e5-9a45-0f323f6b9565.png)

**Comment by Glavin001** [comment]
> Its my suggesstion to kindly have a check the difference between your package and them. 

Since you have both `Altova XML Spy` and `Atom Beautify`, please do this check yourself and show us the differences. Please do not use images and instead copy and paste the text into code blocks, for easier testing on our end. We need examples to test and show breaking cases and will not be re-typing from an image. Thanks!

/cc @prettydiff for XML support in Atom Beautify

**Comment by prettydiff** [comment]
Perhaps the biggest difference between the two is consideration of text nodes adjacent to singleton nodes (self-closing tags terminating in `/>` delimiter). Without knowing the expectations upon the XML in question (in advance) it is safest to presume the greatest number of constraints upon the parsed output. 

For the sake of safety I presume singleton tags to be human consumable content no different than a text node, because in HTML that is exactly the case. If the XML in question does not parse into human consumable text content then the question of creating or deleting text nodes adjacent to singletons is irrelevant. The default parsing scheme for both XML and HTML is to tokenize white space, or collapse all continuous runs of white space into a single character and then convert that one character into a space. If the white space is between two tags it is a text node unto itself. The ramification is that you can be adding or removing spaces from the content that humans consume.

Consider this code example:

    text<a href="someplace.html">text</a>text

If that were beautified into forced indentation it would become:

    text
    <a href="someplace.html">
        text
    </a>
    text

Which would parse into (note the spaces):

    text (hyperlink) text

When the intention is:

    text(hyperlink)text

The same is true of singletons:

    Start a statement<a href="someplace.html"><img src="" alt=""/> text</a>.

Should be parsed into (even after beautification):

    Start a statement(image) text.

Forced indentation should change that to (did you really want that space before your period?):

    Start a statement (image) text .

Pretty Diff does come with an option `force_indent` to provide something closer to the Altova beautification approach. Provide that option with a value `true`. http://prettydiff.com/documentation.xhtml#force_indent

**Comment by shanalikhan1** [comment]
actually Altova XML SPY is not a package but a separate xml parsing tool. I compared your package and that tool result and put in atom and sent you.

**Comment by Glavin001** [comment]
Currently Atom Beautify does not support the `force_indent` option in the Pretty Diff beautifier: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L9-L16

This could be a simple Pull Request:

1) Add the option to the XML language: 
- Pretty Diff option documentation: http://prettydiff.com/documentation.xhtml#force_indent
> force_indent
Description
Allows every piece of code and content in a markup language to be indented without regard for the creation of white space tokens or code semantics.
Type
boolean
Default
false
As labeled in the HTML tool
Force Indentation, Markup Only

- See XML language in Atom Beautify: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/xml.coffee#L22
  - Example of `options`: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/javascript.coffee#L30 

2) Add option to Pretty diff Beautifier's support: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L8
You could simply add `"force_indent": true` to the global options under the `_` (default) namespace.

**Comment by Glavin001** [comment]
I have added many of the missing options to Pretty Diff's beautifier. See #297.

Here are the options for Pretty Diff: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#pretty-diff
- `Force indentation`: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#css---force-indentation-1 

By enabling that it should resolve this issue. Let me know if there are any problems. Thanks!
