### ISSUE TITLE
use project root in for uncrustify config path

### ISSUE THREAD

**Issue by guymguym** [Glavin001/atom-beautify#399]
hi
i saw #235 but I actually want to locate the uncrustify config file on the project root,
just like .jsbeautifyrc because this is a per-project configuration.
thanks!

**Comment by Glavin001** [comment]
The applicable code is here: https://github.com/Glavin001/atom-beautify/blob/c1f09e4f8b441044af40352d67e714a4d5bae8fc/src/beautifiers/uncrustify/index.coffee#L34-L40

It looks like it should in fact use the [TextEditor's path](https://github.com/Glavin001/atom-beautify/blob/c1f09e4f8b441044af40352d67e714a4d5bae8fc/src/beautifiers/uncrustify/index.coffee#L37) and [resolve the absolute path from both editor's path and uncrustify relative path](https://github.com/Glavin001/atom-beautify/blob/c1f09e4f8b441044af40352d67e714a4d5bae8fc/src/beautifiers/uncrustify/index.coffee#L39). This could be adapted to use [atom.project.getPaths](https://atom.io/docs/api/v0.209.0/Project#instance-getPaths) instead of the editor's path.

I would review a Pull Request for such a change. Thanks!

**Comment by guymguym** [comment]
@Glavin001 I would be happy to propose a PR but I don't have any experience with coffee script and atom packages so pretty sure I'm going to write bad code. So I thought I to suggest it in javascript and then translate. What I am not sure is if this - `atom.project.relativizePath(editor.getPath())[0]` returns what we wanted which is the project path of the editor file.

```
let editor = atom.workspace.getActiveTextEditor()
if (!editor) return reject(...);
let dirPath = path.dirname(editor.getPath());
let dirConfigPath = path.resolve(dirPath, configPath);
let projectConfigPath = path.resolve(atom.project.relativizePath(editor.getPath())[0], configPath);
fs.stat(dirConfigPath, (err, stats) => {
  if (!err) return resolve(dirConfigPath);
  if (err.code !== ENOENT) return reject(err);
  fs.stat(projectConfigPath, (err, stats) => {
    if (!err) return resolve(projectConfigPath);
    return reject(err);
  });
});
```
