### ISSUE TITLE
Can Not Update or Install

### ISSUE THREAD

**Issue by WadeShuler** [Glavin001/atom-beautify#404]
For the past few updates (maybe about 2 months now) I have not been able to update Atom Beautify. Finally, I thought I would try to uninstall it and re-install it. I can't install it either. It threw tons of errors, making up for about 2,000 lines in the error log.

Hopefully somone can shed some light on what this error log means:

    Installing “atom-beautify@0.28.5” failed.Hide output…

    > spawn-sync@1.0.11 postinstall C:\Users\Wade\AppData\Local\Temp\apm-install-dir-115517-2028-avzk0n\node_modules\atom-beautify\node_modules\cross-spawn\node_modules\spawn-sync
    > node postinstall

    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: wrong index v1 file size in ./objects/pack/pack-a853a35f50d1b45f28c19aec4a5af860d867f55d.idx
    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: wrong index v1 file size in ./objects/pack/pack-8b8cfe97e3bf6b660a725333c01c6f2c0427554e.idx
    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: wrong index v1 file size in ./objects/pack/pack-c9589b7ffa21bb8442336df4f873fd67ed4513e6.idx
    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: wrong index v1 file size in ./objects/pack/pack-56f3c25fa8b2e6b62c2eb3cefbcfb38cd30c1751.idx
    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: wrong index v1 file size in ./objects/pack/pack-a853a35f50d1b45f28c19aec4a5af860d867f55d.idx
    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: wrong index v1 file size in ./objects/pack/pack-8b8cfe97e3bf6b660a725333c01c6f2c0427554e.idx
    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: wrong index v1 file size in ./objects/pack/pack-c9589b7ffa21bb8442336df4f873fd67ed4513e6.idx
    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: wrong index v1 file size in ./objects/pack/pack-56f3c25fa8b2e6b62c2eb3cefbcfb38cd30c1751.idx
    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: refs/heads/1.0 does not point to a valid object!

    -- truncated --

    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: inflate: data stream error (unknown compression method)
    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: unable to unpack c77a5933f8ed65f6673c7ed717142d4e91237467 header
    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: wrong index v1 file size in ./objects/pack/pack-a853a35f50d1b45f28c19aec4a5af860d867f55d.idx
    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: wrong index v1 file size in ./objects/pack/pack-8b8cfe97e3bf6b660a725333c01c6f2c0427554e.idx
    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: wrong index v1 file size in ./objects/pack/pack-c9589b7ffa21bb8442336df4f873fd67ed4513e6.idx
    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: wrong index v1 file size in ./objects/pack/pack-56f3c25fa8b2e6b62c2eb3cefbcfb38cd30c1751.idx
    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: inflate: data stream error (unknown compression method)
    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) fatal: loose object c77a5933f8ed65f6673c7ed717142d4e91237467 (stored in ./objects/c7/7a5933f8ed65f6673c7ed717142d4e91237467) is corrupt
    npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) fatal: The remote end hung up unexpectedly
    npm ERR! Windows_NT 6.2.9200
    npm ERR! argv "C:\\Users\\Wade\\AppData\\Local\\atom\\app-0.209.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\Wade\\AppData\\Local\\atom\\app-0.209.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Wade\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Wade\\.atom\\.apmrc" "install" "C:\\Users\\Wade\\AppData\\Local\\Temp\\d-115517-2028-syu2rh\\package.tgz" "--target=0.22.0" "--arch=ia32"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.5.1
    npm ERR! code 128

    npm ERR! Command failed: error: wrong index v1 file size in ./objects/pack/pack-a853a35f50d1b45f28c19aec4a5af860d867f55d.idx
    npm ERR! error: wrong index v1 file size in ./objects/pack/pack-8b8cfe97e3bf6b660a725333c01c6f2c0427554e.idx
    npm ERR! error: wrong index v1 file size in ./objects/pack/pack-c9589b7ffa21bb8442336df4f873fd67ed4513e6.idx
    npm ERR! error: wrong index v1 file size in ./objects/pack/pack-56f3c25fa8b2e6b62c2eb3cefbcfb38cd30c1751.idx
    npm ERR! error: wrong index v1 file size in ./objects/pack/pack-a853a35f50d1b45f28c19aec4a5af860d867f55d.idx
    npm ERR! error: wrong index v1 file size in ./objects/pack/pack-8b8cfe97e3bf6b660a725333c01c6f2c0427554e.idx
    npm ERR! error: wrong index v1 file size in ./objects/pack/pack-c9589b7ffa21bb8442336df4f873fd67ed4513e6.idx
    npm ERR! error: wrong index v1 file size in ./objects/pack/pack-56f3c25fa8b2e6b62c2eb3cefbcfb38cd30c1751.idx
    npm ERR! error: refs/heads/1.0 does not point to a valid object!

    -- truncated --

    npm ERR! error: wrong index v1 file size in ./objects/pack/pack-c9589b7ffa21bb8442336df4f873fd67ed4513e6.idx
    npm ERR! error: wrong index v1 file size in ./objects/pack/pack-56f3c25fa8b2e6b62c2eb3cefbcfb38cd30c1751.idx
    npm ERR! error: inflate: data stream error (unknown compression method)
    npm ERR! error: unable to unpack c77a5933f8ed65f6673c7ed717142d4e91237467 header
    npm ERR! error: wrong index v1 file size in ./objects/pack/pack-a853a35f50d1b45f28c19aec4a5af860d867f55d.idx
    npm ERR! error: wrong index v1 file size in ./objects/pack/pack-8b8cfe97e3bf6b660a725333c01c6f2c0427554e.idx
    npm ERR! error: wrong index v1 file size in ./objects/pack/pack-c9589b7ffa21bb8442336df4f873fd67ed4513e6.idx
    npm ERR! error: wrong index v1 file size in ./objects/pack/pack-56f3c25fa8b2e6b62c2eb3cefbcfb38cd30c1751.idx
    npm ERR! error: inflate: data stream error (unknown compression method)
    npm ERR! fatal: loose object c77a5933f8ed65f6673c7ed717142d4e91237467 (stored in ./objects/c7/7a5933f8ed65f6673c7ed717142d4e91237467) is corrupt
    npm ERR! fatal: The remote end hung up unexpectedly
    npm ERR! 
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <http://github.com/npm/npm/issues>

I removed a lot of the duplicate lines because it was 2,000 lines. Atom Beautify seems to be the only package that I have this issue with. I can install and update others without any issues. Seems to be specific to Beautify.

**Comment by Glavin001** [comment]
> spawn-sync@1.0.11 postinstall C:\Users\Wade\AppData\Local\Temp\apm-install-dir-115517-2028-avzk0n\node_modules\atom-beautify\node_modules\cross-spawn\node_modules\spawn-sync

...

> npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: wrong index v1 file size in ./objects/pack/pack-a853a35f50d1b45f28c19aec4a5af860d867f55d.idx


It is because of dependency `cross-spawn` which has dependency `spawn-sync` which appears to use https://github.com/ariya/esprima.git 

I use [`cross-spawn`](https://github.com/IndigoUnited/node-cross-spawn) for Windows support. I only just added that recently, so two months is well over the time when these errors could have happened. No matter what the previous errors were for those past two months, these current errors are with `spawn-sync` and https://github.com/ariya/esprima.git ([which has been a problem a lot, actually](https://github.com/Glavin001/atom-beautify/search?q=https%3A%2F%2Fgithub.com%2Fariya%2Fesprima.git&type=Issues&utf8=%E2%9C%93)).

The [Windows builds are passing on AppVeyor](https://ci.appveyor.com/project/Glavin001/atom-beautify), so it is definitely a personal setup issue and problem is only happen for a small subset of users, if not only yourself. I would recommend maybe even talking with the `npm` team and seeing if there's a problem with your setup, how `npm` uses Git to clone https://github.com/ariya/esprima.git and things related to that. There are a lot of related issues: https://github.com/Glavin001/atom-beautify/search?q=https%3A%2F%2Fgithub.com%2Fariya%2Fesprima.git&type=Issues&utf8=%E2%9C%93 and they usually resolve around firewalls and proxies being the issue. Maybe worth a look through.

Hope you figure it out! Let me know if there's something Atom Beautify specific that I can help with.

**Comment by WadeShuler** [comment]
You are doing something different, that every other extension doesn't. Your package is the ONLY one I have this issue with, and the others use npm as well. So as far as I'm concerned this is an atom beautify problem.

My date was rough. It could be a month or 6 months.. It's been a while.

**Comment by Glavin001** [comment]
I agree, I am doing something different. I am using a different dependency: `cross-sync` in this case because that is what fits the needs of this package, since every package that is not a knockoff of another will likely have different features and needs.
It works on my personal Windows computer and on the Continuous Integration servers for Windows on AppVeyor, so under your own logic this would suggest that you are also doing something different, being the odd man out and the only one in having this issue. 

Regardless, it is neither of our faults, it is simply an underlying problem that we cannot control nor fully understand, yet, and as indicated in your error message above:

> npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

it would seem that talking to the knowledgeable `npm` guys would be a better use of both our time, as it seems we are both surprised and baffled by this error message.

---

Since it does not appear to be clear, I am not simply brushing you off and saying this issue is someone else's problem. I have read your issue and determined that those who would be best to help you and who would actually be able to resolve this problem, are not me and then did some research and suggested direction for where you can take this and potential causes. I could create those issues on their Issue trackers myself, however I am not experiencing this problem and so I would not be able to answer any of their follow-up questions and work towards a solution. Only you can do that. 

> Installing “atom-beautify@0.28.5” failed.Hide output…
>
> > spawn-sync@1.0.11 postinstall C:\Users\Wade\AppData\Local\Temp\apm-install-dir-115517-2028-avzk0n\node_modules\atom-beautify\node_modules\cross-spawn\node_modules\spawn-sync
> > node postinstall

The problem is appearing in the installation stage of Atom Beautify package in Atom, so it is most definitely limiting my ability to fix this within Atom Beautify, as only `apm`, `npm`, and the respective dependency packages are being called at this stage. Specifically, the error is being created in `spawn-sync` in its `postinstall` lifecycle stage which calls `node postinstall`. See https://github.com/ForbesLindesay/spawn-sync/blob/master/postinstall.js for that script.

> npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: wrong index v1 file size in ./objects/pack/pack-56f3c25fa8b2e6b62c2eb3cefbcfb38cd30c1751.idx
npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) error: refs/heads/1.0 does not point to a valid object!

> npm ERR! error: wrong index v1 file size in ./objects/pack/pack-c9589b7ffa21bb8442336df4f873fd67ed4513e6.idx
npm ERR! error: wrong index v1 file size in ./objects/pack/pack-56f3c25fa8b2e6b62c2eb3cefbcfb38cd30c1751.idx
npm ERR! error: inflate: data stream error (unknown compression method)
npm ERR! error: unable to unpack c77a5933f8ed65f6673c7ed717142d4e91237467 header
npm ERR! error: wrong index v1 file size in ./objects/pack/pack-a853a35f50d1b45f28c19aec4a5af860d867f55d.idx
npm ERR! error: wrong index v1 file size in ./objects/pack/pack-8b8cfe97e3bf6b660a725333c01c6f2c0427554e.idx
npm ERR! error: wrong index v1 file size in ./objects/pack/pack-c9589b7ffa21bb8442336df4f873fd67ed4513e6.idx
npm ERR! error: wrong index v1 file size in ./objects/pack/pack-56f3c25fa8b2e6b62c2eb3cefbcfb38cd30c1751.idx
npm ERR! error: inflate: data stream error (unknown compression method)
npm ERR! fatal: loose object c77a5933f8ed65f6673c7ed717142d4e91237467 (stored in ./objects/c7/7a5933f8ed65f6673c7ed717142d4e91237467) is corrupt
npm ERR! fatal: The remote end hung up unexpectedly

It also looks like a Git related issue. I have never seen that error message before and you would have better luck Googling for solutions than I, as you would be able to test them out when you find them. It may also be a good idea to talk to someone who's more familiar with Git errors. It may even be a Git issue that is causing those errors you see in `spawn-sync`s `postinstall` script.

All I could be to simply remove the dependency, `cross-spawn`. Interestingly enough, I am using `cross-spawn` only because of Windows users and Node.js's lack of support for `spawn` on Windows. Feel free to read over https://github.com/joyent/node/issues/2318 for more information if you are interested.

If there is anything that I can do to resolve this issue, such as update dependencies or even switch from `cross-spawn` to a better alternative, let me know. If there are any problems after you get Atom Beautify installed, let me know. Thanks.
