### ISSUE TITLE
Beatify on save causes problems for karma runner

### ISSUE THREAD

**Issue by sjurba** [Glavin001/atom-beautify#440]
When programming Javascript with Beautify on save and Beautify entire file turned on I get some unpredictable behaviour while running unit tests through karma. 

My setup is a standard Angular.js setup: karma, jasmine. I run karma start, and have enabled the autowatch switch in my karma.conf.js. The test run in either PhantomJS or Chrome. Same issue in both browsers.

So the problem is that sometimes when I save the file, karma does not run the latest version of the file, but some previous/old/cached version of the file instead. It seems to be connected somehow to when I save the file an it has some parse error in it. So when it has the parse error it is more likely to run the wrong tests. I have tried disabling all other atom packages, so it does not seem to be connected to any other packages. Also when I turn of the beautify on save feature, the problem seems to go away completely, even if I beautify manually.. 

Finally it seems to be weirdly connected to karma. When ever it runs the wrong/old version of the file, it is always the same version. Even if I restart atom it still show the same behaviour when I resume and it still uses the same wrong/old version of the file as before I restarted. Only when I restart karma does it use a different wrong/old version when the problem starts appearing again. 

To make a wild guess at the cause, perhaps does some sort of cashing of test results perhaps combined with debouncing av file changes. Then maybe atom-beautify issues multiple save commands or something, maybe only when the file contains parse errors..?

**Comment by Glavin001** [comment]
> Then maybe atom-beautify issues multiple save commands

Beautify on Save does trigger multiple save comments. It saves your original contents and then beautifies the saved file contents directly. See https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L406-L437 for related code. This is because Atom's 1.0 API does not work well for asynchronous changes to the text editor buffer on save events. So since I cannot apply a change to the text editor buffer before saving, because some of the beautifiers as asynchronous and not synchronous which the buffer API expects / requires, then I just allow the first save command to complete, and then beautify the file at its path directly, with another function, [`beautifyFilePath`](https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L187).

Feel free to tinker with the beautification lines of code related to beautify on save: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L428-L435

If you can find a solution, please submit a pull request and we can discuss it more.

I am going to review this issue more later today, for now I just wanted to drop a few quick comments and links in case that helps. Hopefully we can figure something out.

**Comment by sjurba** [comment]
Thanks for your feedback. I've looked into it some more, and it seems to be a race condition. I think karma is reading the file while beautify is writing to it (the second time). This means karma reads an empty file.
I think this issue can be solved in karma, so I'm reaching out to them with it.

**Comment by githubsheep** [comment]
Since it seems impossible with the current atom api, what's about to create a shortcut (e.g. override the ```save``` shortcut) which beautifies the file and kicks off save manually?
