### ISSUE TITLE
Failed to install 0.28.7 due to invalid package.json

### ISSUE THREAD

**Issue by tomalec** [Glavin001/atom-beautify#442]
I cannot install the package due to npm error:
```log
Installing “atom-beautify@0.28.7” failed.

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\tomalec\\AppData\\Local\\atom\\app-1.0.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\tomalec\\AppData\\Local\\atom\\app-1.0.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\tomalec\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\tomalec\\.atom\\.apmrc" "install" "C:\\Users\\tomalec\\AppData\\Local\\Temp\\d-11562-9304-nxxsmh\\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! file C:\Users\tomalec\.atom\.apm\atom-space-pen-views\2.0.5\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token 
npm ERR! File: C:\Users\tomalec\.atom\.apm\atom-space-pen-views\2.0.5\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse
```

**Comment by Glavin001** [comment]
> npm ERR! file C:\Users\tomalec\.atom\.apm\atom-space-pen-views\2.0.5\package\package.json

Notice that the error indicates that the problem is in `atom-space-pen-views`. See https://github.com/atom/atom-space-pen-views/blob/master/package.json

I would recommend letting them know. First try uninstalling and reinstalling Atom Beautify. This will force the dependencies to install a fresh copy. If that works, then I would recommend talking to the team for https://github.com/atom/apm and letting them know that `apm` sometimes fails to install all of the dependencies properly.

Let me know how it goes. Thanks!

**Comment by tomalec** [comment]
I cannot re-install atom-beautify as it was not installed, is there any other way to force refresh the dependencies?

**Comment by tomalec** [comment]
atom-space-pen-views issue is at atom/atom-space-pen-views/issues/13

**Comment by Glavin001** [comment]
If it's not even installed, then try again to install and as long as it doesn't use some form of cache then you should have a fresh install. The comment at https://github.com/atom/atom-space-pen-views/issues/13#issuecomment-119875180 is definitely on the right track. You should obviously look at the file that is failing to parse as JSON and see what the problem is. There are many users who are not experiencing this problem, so it is likely a network issue or an intermittent bug with apm/npm when the dependencies were installed. Try to install again and look at the files the errors indicate.

**Comment by tomalec** [comment]
Installing once again did't help.
 Removing around 5 packages from `C:\Users\tomalec\.atom\.apm\` manually with `rm -rf /path/to/dependency/` did the job.

**Comment by Glavin001** [comment]
Wow. Very weird. I would recommend that you create an issue for `apm` at https://github.com/atom/apm because they should definitely know about these installation bugs and I have been seening issues like this more and more lately. Glad it is working for you now.
