### ISSUE TITLE
Can not beautify selected PHP script

### ISSUE THREAD

**Issue by biji** [Glavin001/atom-beautify#453]
Can not beautify selected PHP script (only selection, not whole file)
but when I add <? to my selection, it will do

thanks

**Comment by Glavin001** [comment]
- Could you run `Atom Beautify -  Help Debug Editor` on the file that is not working for you, without `<?`. Let me know results.
- It is likely a problem with one of the PHP beautifiers, such as PHP-CS-Fixer. Which beautifier for PHP are you using? For PHP-CS-Fixer, I'd recommend talking to https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by biji** [comment]
When I debug, **Original File Contents**: contains whole file instead of selected only

Yup, I'm using PHP-CS-Fixer

**Comment by rugk** [comment]
In a selection you would probably have to add php tags (`<?php`) - unless you do this it's not considered PHP code. Maybe that's also the reason why it works with `<?`, because this is the (not recommend) short style PHP tag.

Additionally php-cs-fixer does not seem to be intended to only fix a selection of a file as you can see from the reply there:
> You could fix file, you cannot fix selected part of it.
We use tokenizer to analyse code, and it cannot work on random part of it.

I think this issue can be closed.
