### ISSUE TITLE
Disabled "Beautify On Save" will still trigger beautification dialogue

### ISSUE THREAD

**Issue by tusing** [Glavin001/atom-beautify#455]
Disabling beautify on save doesn't work. The "Beautifying" dialogue (which doesn't seem to adhere to the user theme at all) still pops up. This seems to persist after removing atom-beautify from the command line and reinstalling it.

**Comment by Glavin001** [comment]
Please run Atom command `Atom Beautify - Help Debug Editor` which includes some usable debugging information that I will need.

As of #308 , the `Beautify On Save` option has been removed in place of language specific `beautify on save` options. See this related issue for more details: https://github.com/Glavin001/atom-beautify/issues/405#issuecomment-113151007
This was a while ago, so I am going to assume that this is not the problem and that you are not attempting to use the old `Beautify On Save` option.

Another issue that comes to mind when reading this is #327, "loading dialog pops on save, even when not beautifying". This has since been resolved and no other users have had any more reports of this occurring. However, if there is an existing bug and it is occurring again then I would like to resolve this ASAP and it is high priority. Many users use `Beautify On Save` functionality and I do not want to impede their usual workflow.

Both of the above possibly related issues have been resolved, so it is likely something new. Once I have more information that will help me reproduce this bug then I can work on a fix.
