### ISSUE TITLE
Package Settings View organization

### ISSUE THREAD

**Issue by nikmartin** [Glavin001/atom-beautify#473]
Is it possible to group the settings dialog for atom-beautify by language? Each language's settings are sprinkled throughout the massive list of options. Grouping each language in its own section, and even making a language's settings section collapsible would be great.

**Comment by Glavin001** [comment]
+1 I would also like to group these settings. I am not sure if that is supported.  That would be a question for https://github.com/atom/settings-view 
If it is allows, please let me know!

**Comment by nikmartin** [comment]
https://github.com/atom/settings-view/issues/597

**Comment by Glavin001** [comment]
I'm going to keep this open since I like the idea and want it to exist.

**Comment by nikmartin** [comment]
According to https://github.com/atom/settings-view/issues/597#issuecomment-126655851, settings CAN be grouped. I'm not sure if that fits with the way you build up your config settings from the various included beautifiers

**Comment by Glavin001** [comment]
Excellent! Thanks for looking into this.

**Comment by danielbayley** [comment]
+1.

**Comment by Glavin001** [comment]
So I know that we can group the options with the `object` type. I was originally trying that and experienced this bug: https://github.com/atom/settings-view/issues/386#issuecomment-98379708 
It looks like that has since been resolved.

So now:
- [ ] Atom Beautify could switch back to using the `object` type groupings for nested options
- [ ] Atom Settings View should add some way to collapse these groups (also requested from #620 )

**Comment by Glavin001** [comment]
I think https://github.com/Glavin001/atom-beautify/pull/864 resolves this.
