### ISSUE TITLE
perltidy error when perltidy_profile is an empty string

### ISSUE THREAD

**Issue by Linghui** [Glavin001/atom-beautify#479]
perltidy on pl file makes the file gone empty.
perltidy package works ok itself, but beautify does, so I thought the problem is on beautify side.

**Comment by Glavin001** [comment]
Could you run Atom command `Atom Beautify - Help Debug Editor` and paste the results into a Gist and link here please? Let's try to debug this problem.

**Comment by kelvix** [comment]
@Glavin001 I'll be creeping around your issues list because I find this too fun for the time being... In any case seems to getting caused by [perltidy.coffee](https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/perltidy.coffee#L26). options.perltidy_profile? actually returns an empty string instead of null or undefined causing a stderr of

    "usage: -pro=filename or --profile=filename, no spaces"

Sounds like there would need to be a check for an empty string i.e options.perltidy_profile?.length I can branch and issue a pull request if you'd like.

**Comment by Linghui** [comment]
@Glavin001  I run 'Atom Beautify - Help Debug Editor' , it just open 5 empty files named Beautify, -, Help ,Debug and Editor.

**Comment by kelvix** [comment]
@Linghui I think you used the terminal to perform that command. Not sure if the terminal has an equivalent at the moment for that command. Glavin001 was probably after the results of running that command from the Command Palette. The Command Palette can be found at Packages -> Command Palette -> Toggle. The command in Command Palette in Atom 1.0.2 appears to actually be `Atom Beautify: Help Debug Editor`. 

In addition the file you're debugging on has to have a name.

**Comment by Linghui** [comment]
@kelvix Thank you for the information :) 
@Glavin001 Here is the debug info, https://gist.github.com/Linghui/158a776bcdae006322f7, hope this would help.

**Comment by Glavin001** [comment]
@kelvix I think you are on the right track in your comment https://github.com/Glavin001/atom-beautify/issues/479#issuecomment-124783739 
I would love to receive a Pull Request :smiley: 
Thanks!

**Comment by Glavin001** [comment]
Published to v0.28.9
