### ISSUE TITLE
Beautify on save not working 

### ISSUE THREAD

**Issue by ScriptorNY** [Glavin001/atom-beautify#528]
Hello,

I tried to enable the option to beautify on save, but it doesn't work. When I manually do it, there is absolutely no problem. So I ran the `debug helper`, and [here is the output](https://gist.github.com/ScriptorNY/5e4b9907d70aa67de255).

Thank you very much in advance :)

**Comment by Glavin001** [comment]
Please edit your above Issue to follow the Contributions guidelines outlined in section `New Issues, Bugs, Questions, etc` of https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc

Specifically, move your above debugging logs into a [Gist](https://gist.github.com/) and follow the remaining instructions under 1.
> 1b. Create a new Gist at https://gist.github.com/
1c. Create a file in your new Gist called `debug.md`.
1d. Paste your debugging results from Atom beautify into debug.md file in your Gist.

Thank you.

**Comment by Glavin001** [comment]
@ScriptorNY the problem is that you have put the `language_cpp_beautify_on_save` in your `. jsbeautifyrc` file.

I see that in your `Package Settings` it says: `"language_cpp_beautify_on_save": false,`

If you go into your Atom Beautify package settings and find` Language Config - C++ - Beautify On Save` and change that from `false` to `true` then it should work now for you.

I must apologize, because the [documentation generated](https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md) does not yet know how to handle the `Language Config` options -- they are not allowed to be applied from within `.jsbeautifyrc` file, yet. I will be working on that when I have more time. Unfortunately, for the time being it means that users like yourself may have some troubles getting `Language Config` options to work because you put them in `.jsbeautifyrc`.

Let me know if this does not resolve your issue.

**Comment by ScriptorNY** [comment]
Thank you very much :) I just did that and no problem at all :)

Thank you :)

**Comment by Glavin001** [comment]
Great to hear it is working for you now!

I have updated the documentation generation process: https://github.com/Glavin001/atom-beautify/issues/529

Please take a look at the new documentation and let me know what you think :smiley: 
See https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md

**Comment by sheeley** [comment]
Hey @Glavin001, not sure if my expectations were off, but it took me a bit of searching to understand that I need to toggle languages on individually. Seeing the "Beautify on save" as one of the first options, and having it checked, lead me to believe that there was a bug causing files to not be beautified. 

It's also not terribly easy to find the language-specific save settings (I'm relatively new to Atom, but it seems like searching in a settings view doesn't actually search for settings names). I've now found them, and am checking them individually. It would be nice to have a nuclear option to toggle all languages, which is what I assumed the beautify on save would do. Just my two cents!

**Comment by Glavin001** [comment]
@sheeley I agree and definitely want to improve this workflow for users. I think I need to remove the old `beautify on save` option and also work with the Atom team and https://github.com/atom/settings-view to improve how a large number of options, such as there are with Atom Beautify, are presented and can be organized and searched for. 
Thanks for your feedback! Let me know if you have any other ideas.

**Comment by sheeley** [comment]
Glad to hear. Getting rid of the single button makes sense to me, but I'd still love to have one that actually toggles things, rather than managing each language individually. :+1:
