### ISSUE TITLE
How to achieve great experience with atom-beautify?

### ISSUE THREAD

**Issue by gyzerok** [Glavin001/atom-beautify#550]
It looks like there are really poor set of options to configure JS code style. Since a lot of people uses this package I think there is a way to configure code style more deeply. How do I do that?

**Comment by Glavin001** [comment]
> It looks like there are really poor set of options to configure JS code style.

What configuration options are you missing? Since I want to help you I would appreciate it if you provided some more deep and useful information in your Issue.

> Since a lot of people uses this package I think there is a way to configure code style more deeply.

Atom Beautify uses  [JS Beautify](https://github.com/beautify-web/js-beautify) and [Pretty Diff](prettydiff.com) (/cc @prettydiff ) for Javascript beautification.

Here are the documentation for all of the currently available options for:
- JS Beautify: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#js-beautify
- Pretty Diff: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#pretty-diff

> How do I do that?

You can use a `.jsbeautifyrc` file.
See https://github.com/Glavin001/atom-beautify#configuration
Alternatively, you can use the Atom Beautify package settings from within Atom's settings panel.

**Comment by gyzerok** [comment]
@Glavin001 thank you for such a quick reply!

I'm talking about something like options provided by eslint. In ideal world I'd like to use my .eslintrc for beautifying my code.

For example:
 - Something like autoremove unused variables and imports
 - Swap all variable declarations to `const` and `let`
 - Remove trailing spaces
 - Multilining all for and if statements
 
Guess I can come with more options. Just need to think about them.

**Comment by gyzerok** [comment]
Btw when I am setting braces style I do want to use it for `if` statements, but do not want to use it for imports.

```javascript
// its ok
if {
}
else {
}

// its not ok
import {
  foo
}
from 'foo';
```

**Comment by prettydiff** [comment]
* Removing unused variables is a great idea for an enhancement
* Swapping the `var` keyword to `let` is something that should be done manually, because an automated tool doing this will break your code.  The scope of `let` is different, and so changing it automatically will change it location of declaration and its availability.  Variables are hoisted while areas of the local scope above `let` are a temporal dead zone that will throw errors.
* A single trailing space or new line at the end of the code is something that has been requested more than not, because it is handy for large code that terminates with a really long horizontally scrolled line.
* By multi-lining `for` and `if` you mean adding curly braces where they are optionally neglected Pretty Diff already does this thanks to the `correct` option.  This option inserts curly braces, semicolons, and replaces some `++`/`--` operators with `+=`/`-=`.

I am already accomplishing the request specified in the above comment about import.  I did just notice the `correct` option is improperly adding a semicolon after `foo`.  I have fixed this on my local and it will be included when I publish the next version..... possibly tonight.

**Comment by gyzerok** [comment]
@Glavin001 @prettydiff the problem is I do not see correct option within this atom package options.

**Comment by gyzerok** [comment]
Mb we could try to use [jscodeshift](https://github.com/facebook/jscodeshift) in order to make all the things possible?

**Comment by nmaxcom** [comment]
[**@gyzerok**](https://github.com/gyzerok) commented on [Oct 14, 2015, 7:06 PM GMT+2](https://github.com/Glavin001/atom-beautify/issues/550#issuecomment-148119951 "2015-10-14T17:06:35Z - Replied by Github Comment Enhancer"):
> Mb we could try to use [jscodeshift](https://github.com/facebook/jscodeshift) in order to make all the things possible?

You may want to take a look at [atom-esformatter](https://github.com/sindresorhus/atom-esformatter/), the esformatter port to atom. It has almost 300 settings and [two dozen plugins](https://github.com/millermedeiros/esformatter/wiki/Plugins) (that can make changes to your code)

**Comment by Glavin001** [comment]
esformatter looks great! There is an open issue for adding esformatter support to Atom-Beautify: https://github.com/Glavin001/atom-beautify/issues/1155

I think this will definitely happen in the near future. Thanks!

**Comment by mnburch37167** [comment]
I have embedded JavaScript in an html file, and atom-beautifier removed all trailing commas and trailing semicolons from the code. That really sucks, and should have been considered in the package design. It's not messing with my embedded css code, just the embedded JavaScript code.

**Comment by prettydiff** [comment]
@mnburch37167 That is something that should be a new issue with the debug template.
