### ISSUE TITLE
Tab length for indent is being ignored

### ISSUE THREAD

**Issue by bpinney** [Glavin001/atom-beautify#576]
Atom tab settings are soft tabs, tab length of 4.
Inserting a tab in a file inserts 4 spaces.
Atom Beautify is indenting with two spaces, which I cannot seem to change in the plugin settings. 

Debug information:
https://gist.github.com/bpinney/43bf4686fa645c2cf333

**Comment by Glavin001** [comment]
From your debug logs it looks like the problem is with your existing EditorConfg file. You can see all of the options under the "Beautifier Options" section. "Editor options" Is what you want and "EditorConfg options" is the last to overwrite those options. The options are in order. You can see the result in "Final Options". 

I recommend that you either use the Atom Beautify package settings and change the options for the HTML language or make the changes and store them in a .jsbeautifyrc file.

**Comment by bpinney** [comment]
Thanks for the reply.  In trying to find the offending file, I realized it would be very helpful if the Atom Beautifier debug included the path of the .editorconfig file imported. I can close this issue and open a new one with that suggestion.
