### ISSUE TITLE
CRLF -> LF on .js files

### ISSUE THREAD

**Issue by asser-dk** [Glavin001/atom-beautify#593]
Whenever I run beautify on js files line endings are converted from CRLF to LF (I'm on Windows).

It also seems to disregard any editorconfig settings for this as well. However settings such as `indent_size` is picked up correctly though.

https://gist.github.com/asser-dk/067417979d802ea52dab (contains a debug for a test with and without an .editorconfig file)

To test if other packages were the cause I made a fresh install of atom+atom-beautify but the issue persisted.

**Comment by Glavin001** [comment]
From your debug logs it looks like the beautifier that is being used is `JS Beautify`. I would recommend that you search through Issues over at https://github.com/beautify-web/js-beautify/issues

Also you could try to switch the beautifier from `JS Beautify` to `Pretty Diff`: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#language-config---javascript---default-beautifier

**Comment by prettydiff** [comment]
Tricky topic.  For historical reasons I went and looked back at [ECMA spec 3rd edition](http://ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%203rd%20edition,%20December%201999.pdf) at section 7.2 and the [current spec](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf) at section 11.3.

I could swear I remember seeing the sequence CRLF as a single line terminator somewhere official in the historical documents years ago (when they were current).  At any rate, now it is official in the latest spec that CRLF should be treated as a single character only when evaluating line termination.

To be clear on terminology even though the specifications use the common terms `<CR>` and `<LF>` these characters are actually represented in the language as:

* CR - `\r` or `\u00d`
* LF - `\n` or `\u00a`

This is a tricky thing to evaluate because the DOM does you the helpful favor of converting `\r\n` sequences to `\n` for you, so you cannot even test for this in a browser on any operating system.  The only to test this properly is to use a code editor that supports convenient toggling between various encoding environments.  On Windows I prefer Notepad++ for this as it allows you to immediately convert between various character encoding formats and various environmental formats.  And then you have to test the code analysis directly from a command line tool like prettydiff or js-beautify using only Node from the command line.

My work computer is a Mac, which uses the Unix format of line termination: `<LF>`.  But I will test this on my home Windows computer this evening to ensure Pretty Diff is handling these sequences correctly.

**Comment by asser-dk** [comment]
Odd. I'm not using `JS Beautify` or other equivalents in my projects - unless you're referring to the internals of `atom-beaufity` that is.

I downloaded this package and configured it through `Settings -> Packages -> atom-beautify`

The test I did was a folder that contained only 1 file. The `test.js` file used for the debug output generation above. Later I added the `.editorconfig` file for the 2nd part of the debug output.

**Comment by prettydiff** [comment]
JS Beautify is the default beautifier for JavaScript in the atom-beautify package.

**Comment by madhead** [comment]
Changing to `Pretty Diff` doesn't help. Still get `LF`s after beautifying.

**Comment by prettydiff** [comment]
Would either of you be able to create a gist with a CRLF.  I am having trouble reproducing from my Mac.

**Comment by asser-dk** [comment]
I hope this worked: https://gist.github.com/fc1047371b1fed14bc37

**Comment by mikeleg** [comment]
I have the same problem i can't resolve it. in which is possible to change the end of line

**Comment by prettydiff** [comment]
I have been thinking about this.  The biggest challenge is that you cannot tell if the preference should be `\r\n` or just `\n` from looking at the code.  You can guess with reasonable certainty if you have a direct access to the OS terminal, but this is not a common reality.

Tomorrow I will investigate imposing `\r\n` and hoping it does not create regression problems on my Mac and in various editors.

**Comment by mikeleg** [comment]
Because i use window and change me avery time the end line

**Comment by prettydiff** [comment]
A completed prototype of this option is now available online at http://prettydiff.com/ignore/testlocation

Just scroll down a bit to find the "Line Terminator" option.  I want to do some additional testing before I call this complete.

**Comment by mikeleg** [comment]
I found a solutions installed another plugin on save
