### ISSUE TITLE
Deprecat

### ISSUE THREAD

**Issue by Spy-Seth** [Glavin001/atom-beautify#663]
Since the last Atom update when I run beautify I get a deprecation error and the beautify do not happen:

![screenshot 2015-11-16 11 19 23](https://cloud.githubusercontent.com/assets/95120/11179551/77be80e0-8c54-11e5-9901-cfa57b746a04.png)

Sorry for the screenshot: I cannot copy/past the text.

**Comment by Glavin001** [comment]
Related code for `beautify.coffee` at line 112: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L112

I would recommend creating an issue for https://github.com/atom/atom as well since I think this is actually a problem with Atom's internal code calling `getFileName` which does not exist.

**Comment by Spy-Seth** [comment]
Oh you right! 

See here: https://github.com/atom/atom/issues/9629

**Comment by Glavin001** [comment]
Thanks for looking into it! Hope they can fix it up.

https://github.com/atom/atom/issues/9350
