### ISSUE TITLE
Help with setting up new options

### ISSUE THREAD

**Issue by paperrobots** [Glavin001/atom-beautify#710]
I'm trying to take advantage of a few of the PrettyDiff options like alphasort and selectorlist that I don't see in the Atom-Beautify settings page. I'm not entirely sure I'm doing this correctly. I setup a .jsbeautify file in my user directory. I added this:

```
{
  "alphasort": true,
  "selectorlist": true
}
```

Nothing seems to be happening, so I'm guessing I'm doing something wrong. Any suggestions of what I need to do?

**Comment by Glavin001** [comment]
For reference, here are the Pretty Diff options available in Atom Beautify: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#pretty-diff

I think `alphasort` is now `objsort`? That is what Atom Beautify is using: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L11
/cc @prettydiff 

Here is the internal code for Atom Beautify's Pretty diff beautifier: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L9-L35

If there are options missing, which I can imagine there are since @prettydiff is great at adding new features, then I would recommend someone make a pull request adding those options.

I would then recommend taking a look at https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md

**Comment by prettydiff** [comment]
There is also https://github.com/Glavin001/atom-beautify/issues/524

**Comment by paperrobots** [comment]
Objsort worked for me, thanks!

**Comment by prettydiff** [comment]
Closing as this appears to be resolved.
