### ISSUE TITLE
mixed HTML/PHP, closing tag always on new line

### ISSUE THREAD

**Issue by ftaiolivista** [Glavin001/atom-beautify#724]
When beautify an HTML/PHP  mixed code che php closing after { is always on a new line. How I can prevent that?

![schermata 2015-12-24 alle 10 41 12](https://cloud.githubusercontent.com/assets/150721/11992834/ea1626e0-aa2a-11e5-886d-3648c38edbac.png)

**Comment by prettydiff** [comment]
The issue is whether you are using a PHP document with some HTML or a HTML document containing some PHP, because they use different beautifiers.  I suspect it is the later and if so you get the benefit of Pretty Diff as the beautifier.

Presuming Pretty Diff is the beautifier  The problem is that the PHP tags look mutilated.  It is quite the opposite.  The internals of the PHP tags are fully maintained character for character.  In order to properly beautify the internals of a PHP tag the Pretty Diff application would need to make use of a PHP parser.  At this time Pretty Diff does not use a PHP parser internally.

**Comment by ftaiolivista** [comment]
I'm not sure why but a workaround I found was using the alternate "endif" sintax in php. Using endif instead of brackets does not break the beautify
![schermata 2015-12-28 alle 09 00 51](https://cloud.githubusercontent.com/assets/150721/12015783/ca6c2b90-ad41-11e5-9015-8c1977193034.png)

**Comment by Recursivepaiste** [comment]
I'm experiencing this issue too, whilst it's not the worst thing in the world, it does stop you from getting into the swing of things a bit.
