### ISSUE TITLE
Typescript Generics Failure

### ISSUE THREAD

**Issue by SunburnedGoose** [Glavin001/atom-beautify#725]
I have a generic promise type defined, 

```
private getCookie(): ng.IPromise<string>{
    return this._q.when("");
}
```

When I use beautify, it modifies the angle brackets and breaks my code.

```
private getCookie(): ng.IPromise < string > {
    return this._q.when("");
}
```

It's adding spaces before and after the angle brackets.

**Comment by prettydiff** [comment]
I don't think there is any support for TypeScript yet.  I am working on it though: https://github.com/prettydiff/prettydiff/issues/202

There is huge demand for TSX support.  TSX is easy after providing support for JSX, but actually TypeScript support is a bit more challenging.  It has some semantics, features, and syntax that JavaScript doesn't use.  I still have to work through several use cases that I am not breaking JavaScript and JSX support.

**Comment by SunburnedGoose** [comment]
Thanks.  I've just been getting my arms around TS.  Using it for the mobile port of [Destiny Item Manager](https://github.com/DestinyItemManager/DIM).  The mod has been very helpful.

**Comment by prettydiff** [comment]
I spent more time in Atom Beautify settings and it turns out TypeScript is supported by TypeScript Formatter: https://github.com/vvakame/typescript-formatter

I recommend opening an issue with that project and providing a code sample.  That way they can investigate the problem and provide a solution.

**Comment by prettydiff** [comment]
I have resumed work towards TypeScript support in Pretty Diff.  I am 95% of the way there.  Only one last barrier.  The following TypeScript code breaks JSX support:

    return <any> previous + <any> current;

In JSX it would have to be:

    return <any> previous + </any> current;

I want to offer direct and native support for this, so I have to think through a resolution.  If you are aware of anything I am missing please let me know.

**Comment by Glavin001** [comment]
@prettydiff Why is your example valid TSX?

```
return <any> previous + <any> current;
```

I expect the second `any` to be `</any>` closing the element.

**Comment by prettydiff** [comment]
@Glavin001 TypeScript supports type generics (just like Java since version 7).  A type generic is a custom defined data type assigned to a reference called with angle braces.  So `<string>` would be a generic type named *string*.  Generic types technically aren't tags and don't have a closing pair.

I was able to get Generic Types to work flawlessly for Java and C# but not TypeScript.  The big difference is that TypeScript is essentially JavaScript with added syntax.  That is actually a huge difference in that TypeScript gets native lexical scope support where Java and C# have this hidden behind a convention (lambda expressions).  This differences means that you can return a generic type from a function.

```
var a = function () {
    return <any>;
};
```

My parser isn't smart enough to automagically tell the difference between TypeScript and JSX in this one case because JSX syntax can also return tags directly.  Fortunately, there isn't a collision between the language grammars because TSX changes the syntax of TypeScript to look more like JSX so that it is easier for people to write parsers against.  I solved this problem internally in Pretty Diff by creating a typescript option.  When the typescript option is true `<any>` following a return is a generic type or is an XML start tag if the option is false (the default value).
