### ISSUE TITLE
Error with single quote in comments in Javascript

### ISSUE THREAD

**Issue by vbrajon** [Glavin001/atom-beautify#794]
Hi,

When beautifying an HTML/JS file (this one: http://bl.ocks.org/nbremer/7b051187fe329d705ee9), everything below a script tag is removed if it contains a single quote inside a comment.

The error came from this line:
//Replace all the comma's so that IE can handle it -_-

A fix is to remove the single quote like this:
//Replace all the commas so that IE can handle it -_-

You can easily reproduce this error if you insert `<script>//'</script>` in any html file, everything below will be removed.

**Comment by prettydiff** [comment]
This appears to be a defect in Pretty Diff and not in JSBeautify when using the code `<script>//'</script>` on their respective web tools.  I have attempted the code sample from the link you supplied can cannot reproduce the defect in either of those tools.

Upon second thought I don't think I will fix this issue for : `<script>//'</script>`, because that code should fail.  The comment expects to find a line termination sequence in order to conclude, but the end script tag occurs first.  It is quite reasonable that the end script tag is actually part of the JavaScript comment and thus not actually HTML.  There is no way to know the code author's intention on that matter until the end of file is reached and the code is incomplete as parsed.
