### ISSUE TITLE
XML beautify deletes parts of the file

### ISSUE THREAD

**Issue by vhf** [Glavin001/atom-beautify#812]
Here is the debug report: https://gist.github.com/vhf/395e95d458e976e8f68c

**Comment by prettydiff** [comment]
The problem is https://github.com/prettydiff/prettydiff/blob/master/lib/markuppretty.js#L1190

It is looking for either the absence of a `type` attribute or if the attribute is present with a certain value to determine if the tag represents a wrapper around CSS code.  In this case the `type` attribute is absent so the beautifier expects to parse CSS code, but instead gets more XML code.

I am thinking through solutions without breaking other scenarios in the wild.  I am considering accepting the missing `type` attribute only if there are no attributes present on the tag.  This would solve your problem, but opens the possibility for other negative cases.

I will keep thinking on this and will reach a resolution soon.

**Comment by prettydiff** [comment]
I just published a resolution for this as v1.16.17. You can get the updated code reinstalling Atom Beautify. You just need to update the prettydiff NPM dependency.
