### ISSUE TITLE
Javascript collapse-preserve-inline does not work

### ISSUE THREAD

**Issue by ttsirkia** [Glavin001/atom-beautify#831]
### Description

The new option `collapse-preserve-inline`for Javascript does not work.

### Expected Results

The beautified code should have looked like:

```
var a = {b: 4, c: 5};
```

### Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

### Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/ttsirkia/ea5ec670aae96d6dedb1

**Comment by ttsirkia** [comment]
And the result is the same with the version 0.28.24.

**Comment by ttsirkia** [comment]
If I run js-beautify from command line, the result is the expected so it is not a bug in js-beautify.

```code
> node js-beautify.js -b collapse-preserve-inline test.js
var a = { b: 4, c: 5 };
```

**Comment by Glavin001** [comment]
There was a bug in 0.28.23 ( I pushed a feature I had not finished implementing by accident). Could you please update your debug.md with the latest version of Atom Beautify. Thank you!

Also it appears that the changes made by https://github.com/Glavin001/atom-beautify/pull/779 are still available: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/javascript.coffee#L75-L76

I believe the problem will be because of the bug (incomplete feature) I published. I apologize for this.

I see in your debug.md:
```
 "js": {
        "brace_style": "collapse-preserve-inline",
```

I recommend that you go into your Atom Beautify package settings again and find [`JavaScript - Brace Style`](https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#javascript---brace-style), or set that instead in your `.jsbeautifyrc`.
The feature was regarding the re-organization of the settings and it is not complete. It appears that you have set one of the nested options, which was not working in 0.28.23 (not finished yet) and has been removed in 0.28.24, so you are still experiencing the issue.

This should resolve your problems. Let me know if it does not or if you have any more questions.

**Comment by ttsirkia** [comment]
I already tried this with one computer this morning with the newest version and also changed the settings in the settings view. It didn't work.

Now I upgraded another computer to version 0.28.24 and with this computer it works. I try again with the first computer to see if there was some problems with the upgrade or something else. If there are not any new messages, then everything is fine. Thanks for your response!

**Comment by ttsirkia** [comment]
Just to confirm, it works now also with the first computer. I deleted the plug-in second time but now the settings from config file as well and installed it again.

**Comment by Glavin001** [comment]
Sorry about that. I was working on a separate branch and I must have accidently merged it in because 1 stray commit screwed up all of the settings.

Glad to hear it is working now. I think you and other users will be pleased with the new settings organization once I have completed it :smiley:.

**Comment by ttsirkia** [comment]
No problem. This is one of the best settings in Atom Beautify / JS-Beautify ever.

**Comment by ThomasJT** [comment]
Hello

Is there a way to keep JSX from treating < > as brackets. First below is very readable:

  render(
    <Router>
         <Route path="/" component={Home}/>
    </Router>,
    document.getElementById(container)
  );

But after formatting (js beautify and prettydiff), I get this:
  render( <
    Router >
    <
    Route path = "/"
    component = {
      Home
    }
    /> <
    /Router>,
    document.getElementById(container)
  );

The last bit causes me to grab an extra cup of coffe . Thanks
