### ISSUE TITLE
Plugin install fails

### ISSUE THREAD

**Issue by cyrillk** [Glavin001/atom-beautify#866]
### Description

Plugin install fails
### Expected Results

Plugin installed
### Steps to Reproduce

Install plugin atom-beautify@0.28.26
### Debug

```
events.js:72

    throw er; // Unhandled 'error' event
          ^

Error: ENOENT, open '/Users/kirill/.atom/packages/atom-   beautify/node_modules/handlebars/dist/cjs/handlebars/helpers/block-helper-missing.js'
```
#### How to create `debug.md` Gist

No point to do this.
# Checklist
- [X] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by PierreCBSI** [comment]
Getting a diff error trying to install from within Atom's +Install dir (worth noting: I can't find any npm-debug.log file, the apm dir is missing.... 

Installing “atom-beautify@0.28.26” failed.Hide output…

npm ERR! Darwin 14.5.0

npm ERR! argv "/Users/pjohnson/Downloads/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/pjohnson/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/pjohnson/.atom/.apm/.apmrc" "--userconfig" "/Users/pjohnson/.atom/.apmrc" "install" "/private/var/folders/fp/5v0_20m14v14z6pljmt7w2fxtrqc18/T/d-116222-21431-16m6ett/package.tgz" "--target=0.34.5" "--arch=x64"

npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/expand-home-dir
npm ERR! 404 
npm ERR! 404 'expand-home-dir' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'atom-beautify'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/fp/5v0_20m14v14z6pljmt7w2fxtrqc18/T/apm-install-dir-116222-21431-14ycm0t/npm-debug.log

**Comment by Glavin001** [comment]
@PierreCBSI your error should be resolved now with the closing of https://github.com/Glavin001/atom-beautify/issues/868 
Let me know if there is anything else.

---

@cyrillk : I'm not sure where that error you show is coming from. Did you run `apm install atom-beautify` in your Terminal and that was what it logged out? Is there anything more you could share? In the past, attempting to reinstall Atom-Beautify often resolves similar issues. At first glance I do not see enough information for me to make suggestions on where the problem could be, besides reinstalling since both npm and apm have had many problems in the past while installing Atom-Beautify.

**Comment by PierreCBSI** [comment]
@Glavin001 it's fixed here, installed just fine. Thanks!
