### ISSUE TITLE
Preference settings lost after every new revision of Beautify... 

### ISSUE THREAD

**Issue by emveeoh** [Glavin001/atom-beautify#869]
It would be nice if our preference settings would persist after a package update. Currently, we have to re-apply all of our custom settings anytime you push a revision. Thank you! :)

**Comment by Glavin001** [comment]
Really? This is definitely a bug, since you should not have to reapply all of your custom settings each time. However, Atom Beautify defines only the schema for the settings, it would not change them. 
So this sounds like it would be a bug with either [`apm`](https://github.com/atom/apm), which handles the updating of packages, or [Settings-View](https://github.com/atom/settings-view), which handles the displaying and changing of settings.
