### ISSUE TITLE
Cannot find module './helpers'

### ISSUE THREAD

**Issue by dmynerd78** [Glavin001/atom-beautify#892]
### Description

When saving a file the following error shows up:
![Error popup](http://puu.sh/o63q8/8d78346d2b.png)
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
### Debug

Here is a link to the `debug.md` Gist: [https://gist.github.com/dminer78/e07012ba902061d0730d574c01a3759a](https://gist.github.com/dminer78/e07012ba902061d0730d574c01a3759a)
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
So looking at the stack trace the problem is with `emissary` package, which is used indirectly by `event-kit` which Atom-Beautify uses ( https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L7 ).

In summary, I do not think this is an Atom-Beautify specific bug. It is either a problem with emissary (under event-kit) or a problem with apm not properly installing all of the files for the dependent packages.
Please try to uninstall and reinstall Atom Beautify again. And then also restart Atom before using it (maybe a caching issue, it has happened before). If that does not help, I recommend creating an issue over at https://github.com/atom-archive/emissary/issues or https://github.com/atom/event-kit/issues
Let me know how it goes!

**Comment by dminer78** [comment]
Will do. Thank you for the quick response

**Comment by JJBocanegra** [comment]
@Glavin001 I tried your solution but it doesn't worked :(
