### ISSUE TITLE
windows 10. It doesn' seem to do it in PHP

### ISSUE THREAD

**Issue by midcore-nam** [Glavin001/atom-beautify#903]
https://gist.github.com/midcore-nam/0a588b99eb2dc66e219bcb593faf3751

**Comment by Glavin001** [comment]
Please move your Debugging information into a Gist named `debug.md`.

**Comment by midcore-nam** [comment]
sorry, i'm all new in this game. I installed the cs fixer and i was able to run it from command line. So i located the path to my cs-fixer pasted in atom beautify php setting section. It doesn't seem to beautify my code. Please help.

**Comment by Glavin001** [comment]
It's okay :smiley:.

So looking at your logs I see:
```bash
2016-04-07T19:56:00.244Z - debug: [beautifiers\beautifier.coffee] spawn C:\xampp\php\php.EXE 0=c:\Users\nam\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.BAT, 1=fix, 2=C:\Users\nam\AppData\Local\Temp\temp11637-8744-1hf78gy
2016-04-07T19:56:00.309Z - debug: [beautifiers\beautifier.coffee] spawn done 0  @ECHO OFF
SET BIN_TARGET=%~dp0/../fabpot/php-cs-fixer/php-cs-fixer
php "%BIN_TARGET%" %*
```

The issue is that Atom-Beautify is detecting `c:\Users\nam\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.BAT` as your PHP-CS-Fixer installation however it should be a PHP script instead, `php-cs-fixer.php`.

You can change the PHP-CS-Fixer path in the Atom-Beautify package settings: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#php-cs-fixer-path
I think this issue has been resolved: https://github.com/Glavin001/atom-beautify/issues/670#issuecomment-158092842
> Found the issue... There is more than one location (on windows systems) where files named `php-cs-fixer` live. I tried the other file location (below) and it looks like it was the winner...
>
>Correct path:
`C:\Users\<USERNAME>\AppData\Roaming\Composer\vendor\fabpot\php-cs-fixer\php-cs-fixer`
>
>
>Incorrect path:
`C:\Users\<USERNAME>\AppData\Roaming\Composer\vendor\bin\php-cs-fixer`
>
>Thanks for the diligence on this. Greatly appreciate the help.

Also take a look at other related issues: https://github.com/Glavin001/atom-beautify/search?q=windows+php+cs+fixer&type=Issues&utf8=%E2%9C%93

Let me know if this works for you so others can resolve this issue for them as well.
I hope in the future to improve auto-detection of PHP-CS-Fixer, so the more feedback the better. Thanks!

**Comment by midcore-nam** [comment]
that did it...lol..i copied the wrong path from command line. Thank you :dancers:

**Comment by Glavin001** [comment]
The documentation for supported options for PHP-CS-Fixer can be found at https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#php-cs-fixer
