### ISSUE TITLE
Indent Tabs configuration ignored

### ISSUE THREAD

**Issue by adbayb** [Glavin001/atom-beautify#910]
### Description

The results of beautification are not what I expect.
**Wrong behavior:** "indent_with_tabs" getting ignored (i.e. not override "indent_size" and "indent_char").
**Tested languages:** CSS/SASS, JSX (but for js is working).
**Jsbeautifyrc configuration:**

```
{
    "indent_size": 10,
    "indent_char": " ",
    "indent_with_tabs": true,
    "newline_between_rules": true
}
```
### Expected Results

The beautified code should be indented by tab character but is indented by spaces (length: 10).
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
### Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/ayoubdev/e06689f9317bf31711ca46932d335add

**Comment by Glavin001** [comment]
So the problem is with Atom-Beautify's Pretty Diff beautifier. The option `indent_with_tabs` is not currently supported and `indent_char` is being used without considering `indent_with_tabs`. The applicable line of code is https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L9 
I would be happy to merge a Pull Request adding support for this feature. Thanks!
/cc @prettydiff

**Comment by prettydiff** [comment]
If there any way that if *indent_with_tabs* is set to `true` the *indent_char* value could become `\t` instead of ` `?  Pretty Diff accepts absolutely any string for the *indent_char* option and repeats that string *indent_size* times to create a step of indentation.  A typical tab stop based indentation in Pretty Diff would be

    indent_char: \t,
    indent_size: 1

**Comment by Glavin001** [comment]
For those interested in submitting a Pull Request I recommend:
- changing: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L9
- example: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/coffee-fmt.coffee#L10-L14

**Comment by yrtimiD** [comment]
Same problem with typescript formatter. Would you like a separate issue?

**Comment by Glavin001** [comment]
@yrtimiD : No, I would like a Pull Request making the applicable changes 😃.

For Typescript Formatter I recommend changing the `TypeScript: true` at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/typescript-formatter.coffee#L7 to be more specific to the list of actually supported options found at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/typescript-formatter.coffee#L17-L20 
Pretty Diff has the most complicated option transforms that you can use as an example: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L9-L36

Let me know if you have any questions. Thanks!
