### ISSUE TITLE
Nothing happens when tryin beautify PHP

### ISSUE THREAD

**Issue by avknor** [Glavin001/atom-beautify#918]
### Description

Nothing happens when tryin beautify. Window with plugins logo appears, but thats it. No any action,
no errors, alerts. 

### Expected Results

The beautified code should have looked like: beautifyed code.

```
any code
```

### Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look like beautifyed code!

### Debug

Here is a link to the `debug.md` https://gist.github.com/avknor/278500e4e81a642ccd19d49dde1a3bab

# Checklist

- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by avknor** [comment]
Beautify my issue ;)

**Comment by Glavin001** [comment]
From the logs:
> 2016-04-14T08:45:28.755Z - debug: [beautifiers\beautifier.coffee] spawn C:\OpenServer\modules\php\PHP-5.5\php.EXE 0=C:\Users\KryukovAV.NPR\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.BAT, 1=fix, 2=--level=Symfony, 3=C:\Users\KRYUKO~1.NPR\AppData\Local\Temp\temp116314-15428-ql2s46
2016-04-14T08:45:28.985Z - debug: [beautifiers\beautifier.coffee] spawn done 0  @ECHO OFF
setlocal DISABLEDELAYEDEXPANSION
SET BIN_TARGET=%~dp0/../fabpot/php-cs-fixer/php-cs-fixer
php "%BIN_TARGET%" %*
>
2016-04-14T08:45:28.985Z - verbose: [beautifiers\beautifier.coffee] spawn result 0 @ECHO OFF
setlocal DISABLEDELAYEDEXPANSION
SET BIN_TARGET=%~dp0/../fabpot/php-cs-fixer/php-cs-fixer
php "%BIN_TARGET%" %*

The issue is the same as found in #903.

See https://github.com/Glavin001/atom-beautify/issues/903#issuecomment-207074273 and the many other related issues that solve this problem :+1:.
