### ISSUE TITLE
Wrong end of line.

### ISSUE THREAD

**Issue by adamnguyenit** [Glavin001/atom-beautify#949]
My file has LF end of line, but in atom-beautify version 0.29.7, LF is replaced by CRLF. Version 0.29.6 doesn't have this issue.

**Comment by Glavin001** [comment]
@garretwilson may be of assistance. The Pull Request https://github.com/Glavin001/atom-beautify/pull/941 adds end of line detection support. You may have to set your line ending to `LF` with https://github.com/atom/line-ending-selector

**Comment by garretwilson** [comment]
Hi, Adam. You're on a Windows machine, correct?

In fact the original LF behavior was a bug. On Windows we _expect_ the line endings to be CRLF (unfortunately). Otherwise the files will cause problems with standard workflows and tools such as Git.

However if you've set up your workflow to use LF, simply go into your Atom settings with `Ctrl+,` go to **Packages > Line Ending Selector > Settings**, and then in the settings you can change the **Default line ending** to whatever you like. Yours is probably set to "OS Default", which is why atom-beautify (with the new bugfix) is giving you exactly what you (inadvertently) asked for.

If you're not on Windows and/or your line-ending-selector setting does not say "OS Default", that would be a true bug and we'd need to fix it. Otherwise, please let us know that you found the issue so that this can be closed. Thanks!

**Comment by adamnguyenit** [comment]
Thank you. I changed it. We can close it by now.
