### ISSUE TITLE
.remarkrc file is not respected

### ISSUE THREAD

**Issue by chdsbd** [Glavin001/atom-beautify#965]
### Description

When beautifying markdown using remark, atom-beautify does not respect .remarkrc file in the home directory.
### Expected Results

Atom-beautify should follow the .remarkrc file in home directory by default, just as linter-markdown does.
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

**Comment by ChrisRast** [comment]
Hi @Glavin001, what can I do to address this issue? I have the same problem...
Can you give us indication on where to look if we want to add support for a configuration file for remark?
Thank you for your work!

**Comment by Glavin001** [comment]
Hi @ChrisRast.

Pull Requests welcome! Applicable file is https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/remark.coffee#L39

Please feel free to open the PR earlier than later so I can review and answer questions 😃 .

**Comment by ChrisRast** [comment]
Still an issue, but did not have time & knowledge to address it. :(

**Comment by kachkaev** [comment]
@Glavin001 I'm interested in implementing this feature and submitting a PR. However, there is an issue I'd like to ask @wooorm, the author of remark. It is to do with how `.remarkrc` is searched.

It's great that [`beautify` method](https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/remark.coffee#L35) can receive the fourth parameter called `context`, which means that we have access to `context.filePath` and therefore `path.dirname(context.filePath)`. This is where we should start searching for `.remarkrc` or `.remarkrc.js`. Glancing through `remark` and its parent `unifiedjs` lib I noticed the use of `cwd`, which suggests that this is how _current working directory_ could be defined. However, none of my experiments to set it worked. These are the most sane attempts:

```coffee
modifiedOptions = Object.assign({}, options, {detectConfig: true })
cleanMarkdown = remark({
  cwd: path.dirname(context.filePath)
}).process(text, modifiedOptions).toString()
```

```coffee
modifiedOptions = Object.assign({}, options, {detectConfig: true, cwd: path.dirname(context.filePath) })
cleanMarkdown = remark().process(text, modifiedOptions).toString()
```
@wooorm could you please hint on how to pass `cwd` into remark so that it could find `remarkrc`?

**Comment by kachkaev** [comment]
Ping @wooorm. Will appreciate your help here 🙌

**Comment by wooorm** [comment]
@kachkaev Hi, sorry about that! The stuff you’re looking for isn’t in `unified` or `remark`, but instead in [`unified-engine`](https://github.com/unifiedjs/unified-engine). Specifically here:

https://github.com/unifiedjs/unified-engine/blob/e720037d4bd193af7c15a7964ca8fb9a3e899e7a/lib/configuration.js

Does that help?

P.S. Maybe it makes sense to create something like [`remark-cli`](https://github.com/remarkjs/remark/tree/master/packages/remark-cli#readme) instead of using `remark`!

**Comment by kachkaev** [comment]
Thanks @wooorm, see #2008. Happy to hear your feedback guys!
