### ISSUE TITLE
QUESTION: inline Comments on HTML

### ISSUE THREAD

**Issue by euan-gwd** [Glavin001/atom-beautify#997]
### Description

Hi Gavin
I have looked but been unable to find a solution as yet, perhaps someone can help thanks.
The results of beautification are not what I expected, is there anyway to change the comments to display inline instead of on the next line.

current result:

```
     </div>
     <!--end modal footer-->
   </div>
   <!--end modal-content-->
</div>
<!--end modal-dialog-->
```
### Expected Results

The beautified code should have looked like:

```
      </div>  <!--end modal footer-->
   </div> <!--end modal-content-->
</div> <!--end modal-dialog-->
```
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Checklist
- [x ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue

**Comment by prettydiff** [comment]
The challenge here is that from a syntax perspective there is no way to know if a comment following an end tag should be beautified to the same line as that end tag opposed to appearing on a new line.  In this case the text within the comment suggests the comment describes the end tag, but there is no way to know this from the syntax.

Would you have a suggestion on how this should be approached so that unrelated comments aren't pushed up adjacent to end tags?

**Comment by altair-bryan** [comment]
+1 I'd love to have this feature as well! Prettydiff brings up a good point and a difficult challenge. Context of the comments would be hard to know.

**Comment by prettydiff** [comment]
Closing as this question was answered.  For specific code requests please open issues in the Pretty Diff project directly: https://github.com/prettydiff/prettydiff/issues
